### ISSUE TITLE
Download link in wiki is failing

### ISSUE THREAD

**Issue by Blakeley00** [akarnokd/open-ig#1003]
Download link in wiki is failing

"404. That’s an error.

The requested URL /files/open-ig-launcher.jar was not found on this server. That’s all we know."

**Comment by akarnokd** [comment]
Which page?

**Comment by Blakeley00** [comment]
Here but the launcher link appears to be working now lol. Must have been a temporary site failure that had nothing to do with you guys. :)

[https://github.com/akarnokd/open-ig/wiki](https://github.com/akarnokd/open-ig/wiki)

**Comment by akarnokd** [comment]
Yes, I fixed that now but wanted to make sure that was what you found.
