### ISSUE TITLE
Defensive ground battle without vehicles can't be started

### ISSUE THREAD

**Issue by akarnokd** [akarnokd/open-ig#1005]
From #1004:

> Got attacked on a planet with 2 strongholds and no tanks. For some reason I was still taken to the tank placement screen with all the grids but with no tanks to place the game just got stuck. I couldn’t start the battle and had to force close the game, reload, destroy the strongholds and lose the planet (sadly all my tanks were on a fleet out of range lol) to avoid the bug!

**Comment by p-smith** [comment]
@Blakeley00 Do you have a save before such a ground battle?

**Comment by akarnokd** [comment]
The first ground battle happens at the beginning of rank 2. You can cheat some money (CTRL+G), build fortifications on Achilles, remove tanks, then cheat a level change (CTRL+2) and let it play out.

**Comment by akarnokd** [comment]
You probably have to call the action the "Start Battle" button does instead of going into the deployment mode on the planet screen when the deployment inventory is empty.

**Comment by Blakeley00** [comment]
@p-smith sorry man, I don't have that save anymore. But yeah as akarnokd said its probably not too hard to cheat your way into the same situation.

**Comment by p-smith** [comment]
Thanks for the hints, I got it. PR is incoming.
