### ISSUE TITLE
Fleet retreats on the wrong side of the screen

### ISSUE THREAD

**Issue by akarnokd** [akarnokd/open-ig#1007]
In the video in #1004 at [7:00 minutes](https://youtu.be/ROE_td7mWQY?t=422) the player intercepts the Garthog fleet with the prototype destroyer passing above Achilles. 

In the script related to `Mission17`, once the prototype is destroyed, the remaining ships are forcefully [moved to the right](https://github.com/akarnokd/open-ig/blob/master/src/hu/openig/scripting/missions/Mission17.java#L186) of the battle screen and once the fleet is out of bounds, the battle is won by the player.

In the intercept case, this of course moves them over Achilles' defenses which looks odd and the fleet should exit on the left side instead.

It was a bit long ago but I think there should be a way to check `war` if there is a support planet involved in this space battle and if so, make the forces exit on the left instead.

**Comment by Blakeley00** [comment]
Here's the 'Captain' save that I loaded in the video right before I set the orbital trap for the Garthog.
[Save.zip](https://github.com/akarnokd/open-ig/files/1385300/Save.zip)
