### ISSUE TITLE
Groundwar: Deploy Tanks on Empty Planet

### ISSUE THREAD

**Issue by Barid-86** [akarnokd/open-ig#1013]
Is this still active? I hope it is, awesome game-adoption! :D

When you defend an empty planet (eg. colony center destroyed during combat, all other buildings demolished -> trying to kill off the alien race for re-colonization) you can still add up to 8 tanks.
However, when that planet is attacked you can't deploy them anywhere - no buildings means no spaces to put the tanks. This locks the game, because you can't start the groundwar until all defending tanks are deployed.

Maybe you could add a 3x3 square for unit deployment in the center of an empty planet? Or tie the 8-tanks-limit to an existing colony center? Or enable the "start battle" button even when not all tanks have been deployed?

**Comment by akarnokd** [comment]
Thanks, this is a corner case that was simply ignored so far. If anyone wants to have a shot at this, go ahead.

**Comment by akarnokd** [comment]
Fixed in https://github.com/akarnokd/open-ig/commit/283ea52314051c3bd2f22d30775d21a4bccef70c and will be part of 0.95.215.
