### ISSUE TITLE
Missing resource: es ui/add_production (Game not launching)

### ISSUE THREAD

**Issue by Gexgekko** [akarnokd/open-ig#1014]
I installed the game multiple times and verified it. The launcher still says the game files are damaged.

Here's the log. This message repeats multiple times. I uploaded a clean log with the last time I got the error.

[open-ig.zip](https://github.com/akarnokd/open-ig/files/2251386/open-ig.zip)

**Comment by akarnokd** [comment]
Do not install the spanish language pack as it has never been properly finished.
