### ISSUE TITLE
Cheat Codes

### ISSUE THREAD

**Issue by ViresAnimus** [akarnokd/open-ig#1015]
Is it possible to still use KAROLY? just for credits? I have finished the game a few times but now I like to see how quick i can do it, I still want to take the same time..just have more fun.

**Comment by akarnokd** [comment]
No, we have keyboard shortcuts for cheats: https://github.com/akarnokd/open-ig/wiki/Game-guide#cheats

**Comment by ViresAnimus** [comment]
THANK YOU very much!!
