### ISSUE TITLE
Commander level bug - Garthogs do not attack again if first attack was thrown back

### ISSUE THREAD

**Issue by MichaelW1971** [akarnokd/open-ig#1016]
If the first garthog attack on achilles has been thrown back already in space (without any garthog ground force touching the planet) garthogs will not attack again and the task "Defend Achilles" never will be completed.

**Comment by akarnokd** [comment]
I don't actively develop the game anymore (legal & time concerns) but the quest is supposed to complete if you succeed in any case. As a workaround, let them land for now.

**Comment by MichaelW1971** [comment]
Oh, you did a really great job with the game. Thanks for answering.

**Comment by DrakonAlpha** [comment]
I remember vaguely that this was already a problem with the original. But I may be wrong.

**Comment by akarnokd** [comment]
I think I found the issue. Rarely, Garthogs would flee while they still have battleships and thus vehicles. The success condition only checked for complete Garthog destruction or they losing all battleships. Fixed in 0.95.216.
