### ISSUE TITLE
Auto Build bug - Unupgraded Power Plants are taking too much space

### ISSUE THREAD

**Issue by MichaelW1971** [akarnokd/open-ig#1018]
If population growth affords new big buildings like a stadium or additional hospitals, Auto Build does not tear down unupgraded power plants to make space even if enough energy can be produced by upgrading only one of the existing power plants.

**Comment by akarnokd** [comment]
AI is not supposed to[replace power plants](https://github.com/akarnokd/open-ig/blob/master/src/hu/openig/mechanics/ColonyPlanner.java#L760) if it can build a new one.
