### ISSUE TITLE
problem with the game data

### ISSUE THREAD

**Issue by DrakonAlpha** [akarnokd/open-ig#1021]
It might by an issue: After game installation, when starting the game, I get the following error message. I don't think, I do anythin wrong, so it must be a problem with the game data itself.
[https://s17.directupload.net/images/190603/ofh96wmm.png](https://s17.directupload.net/images/190603/ofh96wmm.png)
Korrect me if I'm wrong, but I think it should work out of the box on any system. I'm using "Java 8 Update 211 64 Bit" and "Java SDK 8 Update 202 64Bit".

**Comment by akarnokd** [comment]
Did you check the Spanish language pack when you installed the game? There is still an issue because of that. I suggest redownloading the game and not selecting Spanish.

**Comment by DrakonAlpha** [comment]
Spanish has not been selected ever. It doesn't become available if I do so. When I installe English (besides German) it's doing something for a while and after that the launcher tells me some files are missing.

**Comment by akarnokd** [comment]
Do you have the launcher in a designated directory? What happens if you approve the repair? Could you post a screenshot of the game directory showing the files that got downloaded?

**Comment by DrakonAlpha** [comment]
It is working, now. The problem was, not having the game files in a dedicated directory. What a stupid error by me.

**Comment by akarnokd** [comment]
Hi and sorry for the delay. This doesn't tell me what the actual error is. Do you have an error log file in your directory? Could you post that?

**Comment by DrakonAlpha** [comment]
There only is a file called open-ig.log within the directory. It contains the information mentioned above, which also appears in the error message when starting the game. Although an error message appears, the game is still running.

**Comment by akarnokd** [comment]
Ah I see now (GitHub hid some lines). There are translations missing apparently. I'll post an update shortly.

**Comment by akarnokd** [comment]
Released 0.95.212 with the fix.
