### ISSUE TITLE
New 0.95.211 update error ruined my game

### ISSUE THREAD

**Issue by cactusmop** [akarnokd/open-ig#1022]
My last IG version was 0.95.210 and my game ran perfectly. When I updated to .211 I get this error.
"java.util.concurrent.executionexception: javax.net.ssl.sslexception: received fatal alert: protocol_version" 

I removed IG game so I could reinstall. However, I am forced to install the .211 version and I get the same error.
I have no idea of where to get my old version back or if It will even do me any good.

I also received the same error as DrakonAlpha.

**Comment by akarnokd** [comment]
You are running with an old version of the Java runtime most likely. What is the version number in the launcher's window title?

**Comment by cactusmop** [comment]
1.7.0_25

**Comment by akarnokd** [comment]
Please upgrade to a newer Java, for example: https://adoptopenjdk.net/

**Comment by cactusmop** [comment]
ok, I update java, but now when i launch game i get "this program does not have a program associated with it for performing this action".  Do I need to restart pc?

**Comment by akarnokd** [comment]
Did you install one of those JDKs from the site I linked? If so, please reinstall Java and chose custom install, then check the option "associate jars" or similar. You can also check out [this](https://stackoverflow.com/a/8511277/61158) entry.

**Comment by cactusmop** [comment]
No, i installed from java.com

**Comment by cactusmop** [comment]
Hmm, .jar doesn't show up on my list.

**Comment by akarnokd** [comment]
Yeah, the latest Oracle installers no longer associate JAR files with the runtime. You have to manually enable this like [this](https://stackoverflow.com/a/394628/61158). The Adopt OpenJDK installers let you set this.

**Comment by cactusmop** [comment]
Thank you so much, IG is now updating
