### ISSUE TITLE
Launcher Icon

### ISSUE THREAD

**Issue by amirulmanaf** [akarnokd/open-ig#1023]
anyone have the original application Imperium Galactica icon file?  it's nice to use in place of the generic java applet icon for the launcher.

thanks in advance!

**Comment by akarnokd** [comment]
I'm not aware of any IG1 icon.

**Comment by DrakonAlpha** [comment]
There is one, but I believe akarnokd doesn't have the copyright to use the icon. If he gives his ok, I'll provide it.

**Comment by akarnokd** [comment]
On Windows, you can customize link icons to the launcher to anything you want. Otherwise, I don't feel like releasing a new launcher just to include a custom window icon, copyrighted or not.

**Comment by amirulmanaf** [comment]
no worries.  was just wondering if yall had one lying around because i used
to have the one provided with the original dos installation and customized
my windows shortcut with it.

thanks for a great port!

**Comment by derekguenther** [comment]
For just your own personal use, I suggest Googling the game and using something you find there.  You can make your own icon files using something like Junior Icon Editor (just be careful when you install it as it tries to package garbage with it, if I remember correctly).  I looked for my original disk but wasn't able to locate it, I'm sure it's in storage somewhere.

**Comment by amirulmanaf** [comment]
understood.  thanks again!
