### ISSUE TITLE
Szint lépés után nem irányíthatók a bolygók.

### ISSUE THREAD

**Issue by Toroco** [akarnokd/open-ig#1027]
Az ötödik szintet 28 bolygóval kezdtem. Miután meg volt az átvezető videó kb 10 bolygó felett elvesztettem az irányítást. Az enyémek maradtak látszólag, látszott a bolygók listáján is, tudtam lerakni épületet, de nem kezdtek el épülni, a csillagtérkép listából is eltűntek, meg állt a kutatás a központok hiányában. Érdekes jelenség

Csak valamelyik Dargslan bolygóra kell küldeni egy kém műholdat, aztán majd jön is a videó
[Anomáliás mentés.zip](https://github.com/akarnokd/open-ig/files/4420004/Anomalias.mentes.zip)

**Comment by akarnokd** [comment]
Igen, a csillagtérkép bolygólistájából is eltűnnek azok a bolygók. Nyomozom.

**Comment by akarnokd** [comment]
Javítottam: 0.95.214.
