### ISSUE TITLE
Csak két kérdés.

### ISSUE THREAD

**Issue by Babjatekos** [akarnokd/open-ig#1029]
Napot!

A első kérdésem az lenne hogy ha a futtatási beállításoknál memória-hoz 1024-et írok akkor elindul a játék, de ha 300 bolygós egyéni játékot akarok 10 fajjal, és nincs bolygó skálázás - 1x-es-  a játék egy végtelen generálásba fullad. Ellenben 200-as bolygószámnál alap 1x-es sklázással elindul. 
Ha 200 bolygónál elkezdem skálázni a bolygókat akkor 2x-nél is a végtelen töltésbe fullad valamiért és csak erőszakkal lehet csak bezárni.

A másik kérdés pedig az lenne hogy ha a futtatási beállításoknál memória-hoz 1024 helyett mondjuk 2048-at adok meg - ergó 2x annyit - el se indul a játék. Ha meg még többet akkor se.
Mintha ez régebben is előjött volna...

Nem buheráltam semmit az xml-ekkel  - még - friss szűzi telepítés, és a java-m is naprakész.
A játék verzióm: 0.95.214

Ötlet? vagy ne is erőltessem a fentebbi dolgokat mert nem fogja bírni? - pedig pár verzióval ezelött simán vitte még a 4x-es sklálázást 300 bolygónál.

**Comment by akarnokd** [comment]
Először is ellenőrizd, hogy 64-bites Java-val fut-e a játék. Lehet, hogy teljesen újra kell telepítened a Java-t.

Másodszor lehet, hogy valami hibára fut a háttérben, és megakad. Indísd ablakos módban és akkor valószínűleg egy hibaablakot fog feldobni.

**Comment by Babjatekos** [comment]
Jelentem problémát megoldotta hogy a Java-t legyalultam, és újra feltettem. De most úgy néz ki hogy rendesen, mert végre 64 bites-t ír - lecsekkoltam először, mert előző verziónál semmit sem írt ki hogy 32 vagy 64, pedig a 64 bitest tettem fel. De lehet hogy csak a 32-est telepítette a 64-es nem pedig azt is kértem, na mind1 szóval legyalutlam és újratettem.

Folyomány: mindkét probléma megoldódott.

Pedig valahol sejthettem volna hogy a java a ludas és ne a játék. Bocsi! :)
