### ISSUE TITLE
Open IG Editor

### ISSUE THREAD

**Issue by Pistapapa** [akarnokd/open-ig#1031]
Üdv! Csak én vagyok ennyire béna, hogy hiába szerkesztgetek ebben az editorban menteni nem igazán találtam meg, hogy hogyan kellene. :)

**Comment by akarnokd** [comment]
Ez editor ex XML fájlt hoz létre, viszont azt kicsit összetettebb beemelni a kampányba.

Mit szeretne pontosan szerkeszteni?

**Comment by akarnokd** [comment]
Úgy látom a mentés nem is működik megfelelően. Az 1x1-es cellákat valamiért nem menti.

**Comment by Pistapapa** [comment]
A Thorin tűzerejét akartam kicsit tuningolni. :)

**Comment by akarnokd** [comment]
A kampányszerkesztő? Azt sosem fejeztem be, úgyhogy nem is igazán működik. Sokkal egyszerűbb volt kézzel XML-t szerkeszteni.

Az open-ig-upgrade-xxx.zip fájlban kell megkeresni a `tech.xml`-t, azon belül a `id='Flagship'` bejegyzést. It meg lehet növelni a fegyver darabszámokat, ami növeli a tűzerőt csak ennél a hajónál. 

A `battle.xml`-ben vannak a fegyverek ereje, pl `projectile id='Laser4'`, de ez mindenkire vonatkozik.

**Comment by Pistapapa** [comment]
Aha köszönöm így már értem hogyan működik.
