### ISSUE TITLE
Vírus

### ISSUE THREAD

**Issue by Pistapapa** [akarnokd/open-ig#1032]
Vírushelyzetben nem keretezi be a bolygóra tartó kereskedőket. Nem lehet tudni amíg meg nem támadod a kereskedőt, hogy most csak arra fele megy vagy tényleg a bolygóra akar e menni. Mikor kifele jön akkor már keretezve van, de előtte is annak kéne lennie. Úgy emlékszem az eredetiben így volt ez.

A San Sterlingre mikor csempész megy akkor keretezi mindet, de vírusnál nem.

**Comment by akarnokd** [comment]
Javítva a [v0.95.218](https://github.com/akarnokd/open-ig/releases/tag/v0.95.218)-ban.

**Comment by Pistapapa** [comment]
Amúgy 23 évnyi IG 1 után emiatt a hiba miatt láttam csak meg milyen egyéb beszélgetések történhetnek a kereskedőkkel, ha nem blokád miatt beszélget velük az ember, szóval ezúton is köszönöm. :)
