### ISSUE TITLE
Can no longer be promoted from Captain

### ISSUE THREAD

**Issue by seven1317** [akarnokd/open-ig#1033]
Hello,

I realise you don't actively develop for this anymore, but I believe your .218 update may have broken something with the Win condition for Captin promotion. I can no longer play past Mission 5 in the Campaign. The mission completes and nothing happens. The Thorin never "shows up", even for months afterwards.

Just thought I put it up here.

Cheers

**Comment by akarnokd** [comment]
Hi. Do you have a save you could share?

**Comment by seven1317** [comment]
I think this one is just before it's supposed to happen? It wouldn't be far
after if not.

Cheers

**Comment by akarnokd** [comment]
You can attach the file with the `gz` extension to this issue.

**Comment by seven1317** [comment]
Save just prior to or after issues

[save-2021-07-11-01-46-56-213.xml.gz](https://github.com/akarnokd/open-ig/files/6795616/save-2021-07-11-01-46-56-213.xml.gz)

**Comment by akarnokd** [comment]
I see the problem. You haven't completed the task to rebuild Achilles. You are missing a Research Lab (any) and Power Plant to make the Spaceport operational again.

**Comment by seven1317** [comment]
Ah I see. The conditions changed from the original objectives where that doesn't matter.

I shall play it thus and thank you for your time in looking at it!

**Comment by akarnokd** [comment]
Yes it is intentional. Gives the players some wiggling room and ensures they start Captain with good economy.
