### ISSUE TITLE
Csillagtérkép korlátozása

### ISSUE THREAD

**Issue by CsoGe** [akarnokd/open-ig#1034]
Szia!

Érdeklődni szeretnék, hogy van-e rá mód, hogy a csillagtérkép határát (az első fejezetekben) visszaállítsd a régi játék méreteire.
Pl. A hagyományos kampány módban nagy segítség volt mindig, hogy a parancsnok szinten a Garthog bolygókon kívül több bolygót is el lehetett foglalni.

Ez megoldható?

Előre is köszi!
Gergő

**Comment by akarnokd** [comment]
Nem rémlik ilyesmi. A kolonizáló hajó csak 4-es rangtól érhető el, úgyhogy se te sem a Garthogok nem tudnak bolygót foglalni.

**Comment by CsoGe** [comment]
Szia!

Nem is a kolonizálásra gondolok, hanem a környező bolygkókra, amit jellemzően a Morgathok kolonizálnak és utána én is el tudom őket foglalni.

Anno mindig nagy előny volt, hogy a parancsnoki szint végére elfoglaltam az összes szektorban lévő bolygót és úgy mentem át admirális módba, így gyorsabban tudtam fejleszteni, mert több bolygóm volt.
Ha gondolod, akkor megkeresem a régi játékot és küldök egy képet, hogy a régi térképhatárok hol helyezkedtek el.

**Comment by CsoGe** [comment]
Így nézett ki a térkép a régi játékban:
http://www.kepfeltoltes.eu/view.php?filename=476IMP1_Mission_3.jpg

[URL=http://www.kepfeltoltes.eu/view.php?filename=476IMP1_Mission_3.jpg][img]http://www.kepfeltoltes.eu/images/2021/09/26/476IMP1_Mission_3_tn.jpg[/img][/URL]

**Comment by akarnokd** [comment]
Köszönöm a képet.

Végiggondolva, attól tartok nem megoldható a kérésed. Az idegenek a 4. rangig teljesen ki vannak zárva a játéktérből, valamint nekik sincs kolonizáló hajójuk. Ez részben azért van, hogy ne zavarjanak be a 3. rang teljesítésébe, illetve hogy ne foglalják el az térképet, ha valakinek tovább tart az első 3 rang.

**Comment by CsoGe** [comment]
Ez okos gondolat, nem tudtam, hogy így van!
Ebben az esetben tárgytalan a kérésem. Azért foglalgattam el régen ezeket a bolygókat, hogy csökkentsem a hátrányomat, mivel addigra a galaxis nagyrészét már belakták! :)

Üdv.
CsoGe

**Comment by CsoGe** [comment]
Még annyi kérdés, hogy ha szabad módban kezdem a játékot, akkor ha jól látom, már parancsnoki szinten ki tudom fejleszteni a kolonizáló hajót. Ez azt jelenti, hogy a többi faj is hamarabb tud terjeszkedni?

**Comment by akarnokd** [comment]
Van egy szabad kampány mód, ahol eleve mindenkinél ki van fejlesztve a kolonizáló hajó. Egyéni játékban a Gazdaság fülön megadhatod, hogy ki legyen-e fejlesztve, ami szintén mindenkire vonatkozik.
