### ISSUE TITLE
0.95.222-23 Lakosság kitelepítésa/kolonia elhagyás

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1038]
Játékot a 222es verzióban kezdtem
Nem tudom pontosan mi volt a fordulópont, működött a funkció, aztán most már nem.
A kolonia elhagyás ablaknál azt irja "abandonplanet.move.notfound" és a kitelepítés/betelepítés sem müködik, gondolom a két dolog összefügg
(amikor elsőre jelentkezett a probléma akkor a játék csinált egy crash savet, de véletlenül töröltem)
Gondolom ez a savegame már kuka és nemtudom megmenteni.

**Comment by akarnokd** [comment]
Milyen nyelven játszol?

**Comment by akarnokd** [comment]
Mindegy, el van írva a címke mindenkinél.

Amúgy akkor van hiba? Tehát az direkt áttelepítés működik de a bolygóelhagyás nem? Van mentésed?
