### ISSUE TITLE
Kolonizáló hajó AI bugok

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1039]
Még az elöző beszélgetésből akkor újra,

Két bolyóra rendeltem kolonizációt, mire az elsöhöz odaért már más faj kolonizálta és ahogy elindult a következő bolygó felé, "ki-be" kapcsolt. Ment megállt, ment megállt és borzalmas lagot generált. Addig laggont amig új utasítást nem adtam neki!

Másik probléma, részben összefügg talán.

Valamiért a gép kolonizáló hajói összeakadtak, több helyen előfordult hogy a kolonizáló hajó rajta állt a bolygón és kész, nem ment végbe a kolonizáció. Az is elöfordult hogy akár két népnek a hajója is ott állt a bolygón. Ez megakasztotta az AI kolonizálását (nagyon sok bolygó maradt szabad) 10-15 kolonizálatlan planéta maradt.

Maga a kolonizálással az AI elég hadilábon áll, amikor a kvota megtelik akkor leáll vele, de elsőre nagyon gyorsan kolonizál a gép, nagyon nehéz értelmes és sok planétát behúzni bizonyos játékokban.

És most hogy fel lehet adni planétát esetleg a gép késöbb is kolonizálhatna ha talál bolygót.

Következő játéknál teszből megduplázom a kvotájukat.

**Comment by akarnokd** [comment]
Javítottam a megáll-elindul hibát. A többit mentés nélkül nehéz lenyomozni.

**Comment by akarnokd** [comment]
Azt hiszem sikerült megtalálni a maradék hibák forrását: a kolonizációs limit nem mentődött el, így újratöltésnél az alapértelmezett faj-értékekkel indult, ami 0 egyeseknél. A 0.95.227-ben benne lesz a javítás.
