### ISSUE TITLE
Teljesítmények amik nem müködnek

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1040]
- Nobel-díj kitüntetést akkor is megkapod ha nincs meg a Ürbázis v2.0
- E.T. létezik-et nem kaptam meg, gondoltam ha nem a garthogok-nál akkor admirális szinten automatikus

**Comment by FaLiar** [comment]
kiegészítés, most megkaptam a "ET létezik"-et, ahogy a radarom felfedezte a garthog bolygót, de miért csak most? a két elöző játékban nem, lehet számit milyen rangon van az ember? most a legelsőben voltam és hard-on

**Comment by akarnokd** [comment]
Az ET csak úgy működött, ha te előbb fedezted fel az idegeneket, mint ők téged. Ezt javítom.

Az nobel díjat még nyomozom.

**Comment by akarnokd** [comment]
Nobel prize: a Thorin is beleszámított, így egyel korábban kaptad meg, mint kellett volna.

Javítottam mindkettőt. https://github.com/akarnokd/open-ig/commit/ff8f1bb0895bae04b5726990631f6832f752a34a
