### ISSUE TITLE
MI felügyelet - auto gyártás

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1041]
tudtam én hogy baj van, nincs ennyi ürbázis a világon :)
https://ibb.co/nzh2XYL

és azon kivül azt jelzi ki minden ürbázisom hogy rakéta 1 van bennük!

https://drive.google.com/drive/folders/1x4AooFkHz5SrLxHaGYetOWynQs3P-KO8?usp=sharing

a 300 tank és 300 vadász nem a bug része :) (vagy mégis?)

**Comment by akarnokd** [comment]
Hogy megmaradjon

![image](https://user-images.githubusercontent.com/1269832/152117700-8698bc8c-b0f3-42c6-809e-447e7a88cb03.png)

**Comment by akarnokd** [comment]
Megtaláltam a hibát, ami miatt a rakétákat rosszul kezelte a logika. Javítottam.

Hogy miért lehetett a megengedettnél több tankot és vadászt, fogalmam sincs. Mindkettőre volt ellenőrzés, hogy ne lehessen többet hozzáadni.

**Comment by akarnokd** [comment]
Javítottam az AI deployment logikán. Lásd 0.95.225.

**Comment by FaLiar** [comment]
azért irtam oda hogy azzal ne foglalkozz mert az nem hiba miatt van ugy, hanem én irtam át
