### ISSUE TITLE
Feketepiac nem müködik

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1048]
nem tudok ürállomást venni!
https://youtu.be/MEFGwkJQYMI
felraktam drivera a save-eket és az error report-ot

+ egy dolog : amikor a müholdat megveszem, ne mondja már hogy "ürhajó" telepítve. az űrbázisnál kb még okés

**Comment by FaLiar** [comment]
hüha, lehet most bohocságot mondtam?! csak oda lehet ahol van katonai ürkikötő?
de akkor miért csinált crash savet?!

**Comment by akarnokd** [comment]
Crash: mert az UI ellenőrző logika inkonzisztens a játékmechanikai logikával. Amúgy lenne rá kiírás, de bugos.

**Comment by FaLiar** [comment]
azt még megkérdem itt, miért nem az invenrotyba kerül minden amit megveszel?

**Comment by akarnokd** [comment]
A globális inventory nem tudja kezelni az egyedi loadoutokat.
