### ISSUE TITLE
unexpected error a_pirate_in_need

### ISSUE THREAD

**Issue by Trokinos** [akarnokd/open-ig#1049]
Hello

After updating to the latest version of Open IG, i started playing the campaign.
While waiting for every repair to complete on Achille i got several traders help , wife message and an escort mission.
Everything was good until a message from another planet telling me they detected battle ships around.

I sent my fleet to attack the location, and after the battle was completed and won, i got an error message popping up (but it didn't crash the game as i could continue to play after that) : 
(XXXXX is my user name)  

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_201
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.95.229
   Command line: [-memonce, -en, -noclickskip]
   Available memory: 193 MB
   Maximum memory: 740 MB
   Parallelism: 4
   Language: en
   Date and time: 2022-02-05T17:51:11.861Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
C:\Users\XXXXXX\Desktop\Open IG\save\default\save-2022-02-05-18-51-11-901.xml.gz
	<entry key='a_pirate_in_need'></entry>
	<entry key='a_pirate_in_need.desc'></entry>

The saved game :  
[save-2022-02-05-18-51-11-901.xml.gz](https://github.com/akarnokd/open-ig/files/8008528/save-2022-02-05-18-51-11-901.xml.gz)

**Comment by akarnokd** [comment]
Thanks for reporting. There is a bug with an achievement in that mission that crashed. I'll fix it and upload a new version shortly. You may have to go back to a save prior to the pirate encounter.
