### ISSUE TITLE
trader rescue is not visible on the starmap

### ISSUE THREAD

**Issue by Trokinos** [akarnokd/open-ig#1050]
Hello,

On the Captain chapter of the main campaign,  at the end of the virus event, the virus carriers appeared so i could go and destroy it to complete the event.  
While i was moving toward the virus carriers, i received the message from a trader being attacked by the aliens.  

But nowhere on the starmap the location had appeared, so i thought maybe it would appear after i destroy the virus carrier. Unfortunately even after completing the virus event, the trader location was still not appearing.  

Wouldn't be a real problem but  as unfortunately the campaign does not allow failure in a mission (because after failing an objective you always receive a message from Command that will fire you) it also means you have a game over coming .  

I added the saved game :   
[save-2022-02-06-15-37-23-468.xml.gz](https://github.com/akarnokd/open-ig/files/8010402/save-2022-02-06-15-37-23-468.xml.gz)

**Comment by akarnokd** [comment]
They are in a region not covered by radar:

![image](https://user-images.githubusercontent.com/1269832/152687054-9b92d8a6-2608-49de-9ffd-f3d9d980a89b.png)

**Comment by akarnokd** [comment]
Without cheating:
![image](https://user-images.githubusercontent.com/1269832/152687183-91d43e97-aec0-4288-886d-ca5cce8d9020.png)

**Comment by Trokinos** [comment]
Ah ok thanks, i didn't thought they could appear outside of the system radars.
