### ISSUE TITLE
Felszerelés képernyő ápdét

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1053]
Multkor kihagytam valamiért,

szeretném kérni hogy a felszerelés képernyőn a "elvesz" és "hozzáad" parancsokat is lehessen shift-el használni, hogy 10esével rakjak fel tankot vagy bármit illetve amikor leszerelek valamit, ne kelljen annyit klikkelni.

**Comment by FaLiar** [comment]
ha szépen nézek ezt megcsinálod? :) pusziért?

**Comment by akarnokd** [comment]
Miért kell ilyen stílusban beszélni?

**Comment by FaLiar** [comment]
vicces akartam lenni, látom félre ment. köszi a gombot!
