### ISSUE TITLE
Technologia foglalás / bolygófoglalás

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1057]
Leirtam a problémát, de nemtudom mi a megfelelő megoldás rá.

Egyéni beállítás :  1. "Nem lehet épületet foglalni" Nem bontja le az új épületeket DE újat nem tudsz építeni. 
"Lehet épületet foglani, DE a félkész épület lebomtásra kerül" Igy nem lehet mezont/bolygopajzsot foglalni. Esetleg ez csak az ágyukra és pajzsra vonatkozzon, más épületet ne bontson le, pl civil épületeket.
A kérdés áll amit privátba irtam. "AI tud technologiát foglani másik AItól/vagy tölem) itt is a mezon a lényeg és a bp2

**Comment by akarnokd** [comment]
> A bolygófoglalásnál az épületfoglalás, ez azért nagyon imballance, mert itt a félig kész épületek nem rombolodnak le, mint a simába, ergo az admirális szint egy ychom bolygó és van bolygopajzs2 + mezon. és semmit nem kell érte tenni.
Ez lehet hülyeség amit irok, de a gép AIk egymástol is elopnak találmánmyokat, és a végén már mindenki mezon+bolygopajzs2-t épít. (ha nem igy van majd kijavítasz)

**Comment by FaLiar** [comment]
most nem értem, ez bug volt? te sem igy akartad?

**Comment by akarnokd** [comment]
Ja, már egy ideje javítani kellett volna.
