### ISSUE TITLE
A Thorin probléma

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1058]
Esetleg ez is egyedi beállítás lehetőség hogy lehet e plusz thorint venni feketepiacról.
(nemtudom, legyen drágább, csak akkor tudj venni ha már van csatahajó3-ad, ötletelek csak)

**Comment by akarnokd** [comment]
Nem lenne szabad, hogy a kampányban plusz Thorint vegyenek a játékosok. Majd letiltom.

**Comment by FaLiar** [comment]
igen? :) pedig jó moka, csak op. ezért is mondtam hogy kapcsolható legyen
