### ISSUE TITLE
Nincs hang / no sound

### ISSUE THREAD

**Issue by Gud-Git** [akarnokd/open-ig#1063]
Szia!

Először is nagyon köszönöm, hogy foglalkozol ezzel a gyöngyszemmel.

Sajnos a legújabb változatban teljesen elromlott a hang.

Csak egy pittyenés hallatszik indításkor, de utána semmi.

**Comment by akarnokd** [comment]
Üdv.

A hang tekintetében nem történt változás évek óta, úgyhogy a probléma máshol lehet. A Linux és Mac rendszerek szoktak csak úgy nem működni. Kérlek, nézd végig a [hibakeresési útmutatót](https://github.com/akarnokd/open-ig/wiki/Troubleshooting).
