### ISSUE TITLE
Skirmish Space Battle Bug

### ISSUE THREAD

**Issue by Brian12345678999** [akarnokd/open-ig#1066]
I have started on the skirmish part of the game.  Always a dream of mine to do something besides the original campaign which I know by heart.  Got a full level 1 fleet with 3 flagships, 24 destroyers type 1 and 30 fighters.  All level 1 and completely full of weapons and equipment.  Went to battle an Alien planet with no planet guns but 30 level 1 fighters.  The Alien fighters completely destroyed every ship I had and did not fire back.  Do we have to manually select every ship and give them a target??  The original game did not need this. The player ships just attack the closest target on their own.  You do have the option to manually select targets and the player ship will move and attack them that way.  Considering this project is at least 10 years old I was very disappointed to be honest.  Thanks.

**Comment by akarnokd** [comment]
You have to select the ships and select "Guard" mode manually.

**Comment by Brian12345678999** [comment]
Thanks good to know.  I will try that later on.
