### ISSUE TITLE
Csata kiértékelése

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1068]
AI támadja bolygómat, elvesztem ürcsatát de megnyerem a földit, az erödöket rosszul számoja el, (rossz helyre)
(értékelés kép)
Én támadok bolygót, nyerés-nyerés, nem irja hogy megnyertem az ürcsatát, (nem nagy dolog de mégis)
(erre nincs kép)

**Comment by akarnokd** [comment]
> (értékelés kép)

A kép lemaradt.

**Comment by akarnokd** [comment]
Megtaláltam a hibát. Javítottam.
