### ISSUE TITLE
Bolygó felszin és járművek

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1070]
ha az ember a felszini göröngyöket legyalulja a játék még ugy érzékeli hogy ott van valami és a jármüvek pirosak lesznek, mintha takarásban lennének

**Comment by akarnokd** [comment]
Kijavítottam, de nem teszteltem. Ha harc közelében vagy, légyszi próbáld ki.

**Comment by FaLiar** [comment]
tesztelem
