### ISSUE TITLE
Centronoom kormányzó érkezése

### ISSUE THREAD

**Issue by Pistapapa** [akarnokd/open-ig#1076]
Ez csak egy apróság, de amikor a kampányban érkezik a Centronom kormányzója és kisérni kell, a San Sterlingről indul nem a Centronomról. :)

**Comment by akarnokd** [comment]
https://youtu.be/chW9_RmkfVc?list=PLFTDBbYrcivrjq8JgUTK7sGjmp6Wol_RK&t=214

Az eredetiben sem a Centronom tól/felé megy, hanem a San Sterling mellől.
