### ISSUE TITLE
építési probléma

### ISSUE THREAD

**Issue by Pistapapa** [akarnokd/open-ig#1078]
Tapasztalok egy olyan hibát főkampány módban, hogy ha elfoglalok a Garthogoktól egy olyan bolygót ahol van kereskedőközpont, akkor automatikusan nem fogom tudni építeni a bolygóimon, viszont hogyha mentek egyet és betöltöm a mentést akkor utána már tudom építeni.

**Comment by akarnokd** [comment]
Fel tudnál tölteni egy mentést, ami az elfoglalás előtt van?

**Comment by Pistapapa** [comment]
Az élelmiszergyár megjelenik az építhető épületek között, de a kereskedelmi központ az nem.

[kereskedelmikozponthiba.zip](https://github.com/akarnokd/open-ig/files/11782570/kereskedelmikozponthiba.zip)
