### ISSUE TITLE
Párologtató update leírás hiba

### ISSUE THREAD

**Issue by Shadowbummer** [akarnokd/open-ig#1079]
A párologtató update-jének leírásában az szerepel, hogy 250%-ra növeli a lakóteret. Nem az lenne a helyes, hogy a népesség növekedési ütemet emeli ennyivel? Köszi, ha ránézel! Képet is csatolom.

![Parologtato_update_leiras_hiba](https://github.com/akarnokd/open-ig/assets/141014043/862929c6-cd6d-4d1e-8140-90477b42d906)

**Comment by akarnokd** [comment]
Kijavítottam.
