### ISSUE TITLE
Feature: "mindet elad" opció

### ISSUE THREAD

**Issue by Shadowbummer** [akarnokd/open-ig#1084]
Új technológiára váltásnál előfordul, hogy rengeteg marad raktáron az előzőből (pl. lézer technológia váltás). Megkönnyítené a játékot, ha lenne egy "mindet eladja" gomb is és nem kellene az "elad" gombot nyomogatni sokáig, hogy mindegyik darabtól megszabaduljunk.

**Comment by akarnokd** [comment]
Nem tervezem. A Ctrl + Shift nyomva tartása mellett százassával ad el.

**Comment by Shadowbummer** [comment]
Köszi, ez elkerülte a figyelmem.
