### ISSUE TITLE
archive.org download of Open-IG-0.95.X.zip: launcher not checking in source dir and downloads still from Github

### ISSUE THREAD

**Issue by murkymark** [akarnokd/open-ig#1098]
Installation via launcher does unexpected things - minor issue.

I've downloaded "Open-IG-0.95.X.zip" from archive.org as suggested.
Then I've unpacked it, went into the unpacked folder and startet "open-ig-launcher.jar".
It gave me an "Install" option. Of course I created a new folder when it asked for the installation target.

Now the launcher checked the destination folder for data files (nothing found of course) and downloaded all data files from Github although they where on the same directory level as the launcher already.

The launcher moved itself from the folder I had unpacked ("Open-IG-0.95.X.zip") to the target folder, so it removed itself from the source folder. Self deleting setup files are not cool! The Launcher should really not delete files I have placed manually somewhere, even if it is the launcher file itself.

**Suggestion:**
Show a radio button option to select the data file source before actual installation:
    Option 0: use or install data files from selected folder (text input + button to select path with mouse + verify button) - default
    Option 1: download from "https://archive.org/download/open-ig-0.95.-x/"
    Option 2: download from "https://github.com/akarnokd/open-ig/"

**Comment by akarnokd** [comment]
You did something wrong, the installer should pick up files in its current directory by default. Are you on Linux?

**Comment by akarnokd** [comment]
This how it is supposed to install:

- Unpack `Open-IG-0.95.X.zip` into a directory where the game will live, such as `C:\Games\Open-IG`.
- Run the launcher, click install, select language packs.
- Select the same directory where the files have been extracted, such as `C:\Games\Open-IG`.
- The launcher will verify existing files and download the remaining files from GitHub.

**Comment by murkymark** [comment]
It's Windows but shouldn't be the cause.
I double clicked "open-ig-launcher.jar" in the file manager to start it.

I did as you said and installation goes too slow for a copy operation on an SSD. Network traffic monitoring showed data transmission during installation and the launcher shows "Downloading".

This line is called before it checks for any existing files [https://github.com/akarnokd/open-ig/blob/master/src/hu/openig/launcher/Launcher.java#L1748] in the working directory.
From there I can not see a file check in the source directory (working directory).

An installation logfile in the target directory would be useful.

**Comment by akarnokd** [comment]
The Launcher does not copy the game files from the Archive.org zip/torrent. If it can't find them intact in the target install directory, it will download them from GitHub. If done correctly, only the game jar and data zip will be downloaded.

Did you try to install it into a restricted directory such as `Program Files`? Do you have a 3rd party antivirus? When you extracted the big zip, did you use Windows for it, which creates a subdirectory by default so it would look like `C:\Games\Open-IG\Open-IG-0.95.X\`?

**Comment by murkymark** [comment]
> The Launcher does not copy the game files from the Archive.org zip/torrent. If it can't find them intact in the target install directory, it will download them from GitHub. If done correctly, only the game jar and data zip will be downloaded.

That's what I was telling all along.
The installer doesn't give the option to use the data zip files from the local source directory and doesn't automatically check there. This makes installing with the launcher from the source directory without internet connection not working.
Also [README.md](https://github.com/akarnokd/open-ig/tree/master#readme) doesn't say that manual copying is needed.
Most people will probably do as I and won't preserve Github bandwidth that way.

**Comment by akarnokd** [comment]
The Archive zip doesn't contain the jar and data zip because that changes way more often than the other assets. Those are always downloaded thus internet is required. Then you can copy the whole directory to an offline machine if needed.

The Launcher has been working like this for 9 years so far with thousands of successful installs. In the early days, people downloaded just the launcher to some download directory, which wasn't the final place, hence the self moving nature of the Launcher. It then downloaded the rest to its new working directory. The difference now is that people supposedly unzip the Archive zip to the designated directory themselves and let the Launcher download the rest.

Anyway, I don't plan to change the Launcher in the foreseeable future.

**Comment by murkymark** [comment]
> The Archive zip doesn't contain the jar and data zip because that changes way more often than the other assets.

This archive (Open-IG-0.95.X.zip) contains "open-ig-launcher.jar" already and that's the one I've started after unpacking.
