### ISSUE TITLE
XMF format information

### ISSUE THREAD

**Issue by murkymark** [akarnokd/open-ig#1099]
Just for your info and for the wiki.

It seems the XMF format is linked to the Hungarian demo scene group AstroideA which is linked to the developers at Digital Reality.
The group member Reptile (Balazs Vasvari) made several XMF music tracks: http://ftp.modland.com/pub/modules/Astroidea%20XMF/Reptile%20(HU)/
I suppose Balazs Vasvari created the tracker for the demo group around 1995 and Tamás Kreiner used it for the music in the game.

LibOpenMPT and the Tracker OpenMPT can open and play XMF files recently, their documentation calls the format "Astroidea XMF" (https://wiki.openmpt.org/Manual:_Module_formats#Choosing_a_module_format).

LibXMP supports playback too, the format list calls it "XMF Imperium Galactica" (https://github.com/libxmp/libxmp/blob/master/docs/formats.txt).

**Comment by akarnokd** [comment]
I know. I spent two weeks reverse engineering it back in March.

https://github.com/akarnokd/open-ig-audio-tools

Also one of the contributors [looked into it](https://github.com/Konstanty/libmodplug/issues/94#issuecomment-1469440377) hence the libxmp support now.
