### ISSUE TITLE
can't get to work

### ISSUE THREAD

**Issue by law7441** [akarnokd/open-ig#1100]
not sure anyone still around, having issue getting these work, before got winsdows 10 had no issues now it just simple can understand how to get it to work and could be missing something it not susprise me. 

if anyone help it be appreciated.

files in question
![Uploading IG.jpg…]()

**Comment by akarnokd** [comment]
How is it not working? Did you install Java? During the install, did you click "associate jar"?

**Comment by law7441** [comment]
Not even getting that far, don't run installation just show code etc and
extracted files, never had these issue. Beforehand maybe am doing something
wrong.

**Comment by derekguenther** [comment]
You'll need to provide a lot more information to get good help.  It looks like you tried to upload an image, but the link for it just directs back to this GitHub issue.  We need to know exactly what you're seeing and when, with as many details as you can provide:  "While trying to do X, I click on Y, and I see an error box which says Z."  Screenshots, if you can get them to upload properly, would be very helpful; if you can't get them to work you'll need to type out what the error message says.

**Comment by law7441** [comment]
Ok will do, I add everything soon as I can.

**Comment by akarnokd** [comment]
I presume you have 7zip or WinRar installed, which tend to override the program associations for jar files. Try reinstalling the Java runtime and make sure you select "associate jar".

![image](https://github.com/akarnokd/open-ig/assets/1269832/75341035-29a9-4dbf-a561-c89e3f3af9ef)


Otherwise, you'll have to use command line and run `java -jar open-ig-launcher.jar`.

**Comment by law7441** [comment]
Will do and ty for getting back me so soon.

**Comment by law7441** [comment]
![image](https://github.com/akarnokd/open-ig/assets/18325136/55d56116-68e0-4d47-bed7-12d28e53ba16)

these now installed

but download and extract the files but simple not alone run any of files in question. 

all folders just don't let do anything.

![IG](https://github.com/akarnokd/open-ig/assets/18325136/4583c1f7-9666-49b6-a23f-c7be3512465d)
![IG1](https://github.com/akarnokd/open-ig/assets/18325136/91459e78-ebc6-48a2-8513-116eebeef581)
![IG2](https://github.com/akarnokd/open-ig/assets/18325136/5072e756-5e1c-45d4-8b78-6581f9bdf810)

**Comment by law7441** [comment]
.iml just how to open it
![image](https://github.com/akarnokd/open-ig/assets/18325136/b407a16f-f040-4965-819a-3fbd78bd13ab)

**Comment by law7441** [comment]
not sure these matters or not but do have gog copy installed on my computer, your way better verison special screen resolation and upgrading building etc.

**Comment by derekguenther** [comment]
In one of your screenshots, the one showing Games > IG in the address bar of your file explorer, all of the files are associated with WinRAR.  Java .jar files _can_ be opened with WinRAR to extract specific things from them, that's probably how you accidentally associated .jar with WinRAR.  You need to open open-ig-launcher.jar with Java.

Right-click it and choose "Open With..." which will bring up a dialog asking you to choose the program.  Locate Java's .exe and use it to open the launcher, that should do the trick.

**Comment by law7441** [comment]
is these right file?
![image](https://github.com/akarnokd/open-ig/assets/18325136/6b017088-4455-4b9f-987d-e8eaf0a8033d)

**Comment by akarnokd** [comment]
Open With... might not work with Java 8.

Just create a `run.bat` in the Open-IG directory with the following content:

```
javaw -jar open-ig-launcher.jar
```

Run that bat.

**Comment by akarnokd** [comment]
Also please install a newer Java, v11 minimum, best, v21 to avoid some issues.

**Comment by law7441** [comment]
I updated to v20 and no idea how to do that, more happy to give remote access if that easier?
email law7441@googlemail.com.

**Comment by akarnokd** [comment]
Open Notepad, copy-paste that line, then Save as `run.bat` into the Open-IG directory.

**Comment by law7441** [comment]
that did launch the installer and after clicking install come up with these 
![image](https://github.com/akarnokd/open-ig/assets/18325136/e9f80bc6-02a6-45f8-9e22-142f22265390)
![image](https://github.com/akarnokd/open-ig/assets/18325136/cd7ee841-32ac-40dc-8769-0d64b72842c7)

**Comment by law7441** [comment]
just want also apologise for being hard work here.

**Comment by akarnokd** [comment]
Are you in a restricted network? Do you have any 3rd party antivirus (i.e., not Windows Defender)?

**Comment by law7441** [comment]
good news it working now as did java 20 not 21 and now do that have installed and game is accessable.
thank you so much and sorry for taking ages to get there.

**Comment by derekguenther** [comment]
@law7441 Glad it worked out!
@akarnokd I hope I was some help, I know supporting stuff like this can be difficult on top of developing and having a life.  Really appreciate the work you do!

**Comment by law7441** [comment]
Ty @derekguenther  and yes love these game and work he done for it is amazing.
