### ISSUE TITLE
Proposed trading changes

### ISSUE THREAD

**Issue by ferencdg** [akarnokd/open-ig#1110]
I really like that trading was added, but I wish it was a bit more similar to IG2. I made some small changes locally, let me know if you are interested in merging it, then I would raise a PR.

1. The buying price for the ships and weapons is now random, and sometimes it can be lower than the base cost. 
2. Alien ships and weapons can also be bought on the market, as long as some of the aliens already researched it. The ships would be limited to destroyers and above. (Allowing the purchase of alien fighters would be pointless as they cannot be equipped in the current GUI)

Both are something that is in IG2, but maybe they break the game balance.

**Comment by akarnokd** [comment]
Thanks for the interest but there are no plans or need to rebalance trading in general.
