### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by milepexel** [akarnokd/open-ig#1111]
[crash log.txt](https://github.com/akarnokd/open-ig/files/13623294/crash.log.txt)

![no-speakers](https://github.com/akarnokd/open-ig/assets/149858161/601d2f60-898b-44ca-9f5e-467278c11282)

There is no speakers connected. May be the reason in this? Because when it connected - all works! Thank to You all for Your attention.
(google translation ru->en)

**Comment by akarnokd** [comment]
What is your system. Don't you have an integrated audio device? By speaker, do you mean one of those USB-based headphones?

Yes, the game expects to have an audio device available. I can't say if and when we account for your unique situation.

**Comment by milepexel** [comment]
> What is your system. Don't you have an integrated audio device? By speaker, do you mean one of those USB-based headphones?
> 
> Yes, the game expects to have an audio device available. I can't say if and when we account for your unique situation.
- amd64, Windows 10 21h2, Windows Feature Experience Pack 1000.19053.1000.0, build 19044.3693
- I have onboard audio device and have installed audio drivers too.
 - The game crashes in case 'no speakers connected to MB's backpanel mini-jack 3.5mm'. Just OS can't detect speakers but HD audio device is present and work normally.
Here is not a problem. I only submit it. Thank You.
