### ISSUE TITLE
 Hiányzó videó

### ISSUE THREAD

**Issue by Peterfiafekete** [akarnokd/open-ig#1112]
Üdvözlöm a kedves fejlesztőket!
Az OpenIG videólejátszójában találtam a "douglas_fire_1_battle" című videót. A forráskód alapján a Mission19.java állományban van róla utalás ( loseGameMessageAndMovie("Douglas-Fire-Battle", "lose/fired_level_3"); ). Ezt a 19. küldetést (Zeuson bolygó blokádja)  több módon is próbáltam elveszíteni, mégsem jelenik meg ez a videó a sikertelen küldetés végén. Milyen esetben lehet ezt a videót előidéztetni? Válaszukat előre is köszönöm.

**Comment by akarnokd** [comment]
Az elbukás körülményei:
- a kormányzó elhagyta a szektort
- a harcban a hajója megsemmisül.

**Comment by akarnokd** [comment]
Á értem.

Jelenleg az a videó nincs becsatlakoztatva semmilyen küldetéshez vagy eseményhez, így nem lehet látni a játékon belül.

**Comment by Peterfiafekete** [comment]
Köszönöm szépen a választ, kedves Dávid!
Ne tudja véletlenül, hogy az eredeti Imperium Galactica játékban hogyan lehet előidézni? Köszönöm előre is.

**Comment by akarnokd** [comment]
Biztosan nem tudom. A szöveg alapján néhány csatát el kell veszteni (úgy, hogy közben a parancsnoki hajó ne semmisüljön meg, tehát másodlagos flottával).

Közben az Open-IG 0.95.242-ben betettem egy új feltételt, ami előhozza ezt a vesztési módot: 4 db űr vagy földi-csatát kell veszteni. Annyi a nehézség, hogy a korai játékban több vesztési feltétel is van, ami megelőzheti ezt az új feltételt.
