### ISSUE TITLE
background AI

### ISSUE THREAD

**Issue by andras-kiss** [akarnokd/open-ig#1113]
Does the simulation  of other empires work in the background during lvl1 and lvl2? I notice that console messages in the background start only when I reach lvl3. If other empires are in a pause state during lvl1 and lvl2 then there is no need to rush advancing to lvl2 and lvl3, only to lvl4 and beyond. Can someone answer this with certainty?

**Comment by akarnokd** [comment]
They are forbidden to plan for attacks and are boxed in. Otherwise their economy is active and will create defenses over time. Thus spending too much time in ranks 1 and 2 may result in a more difficult rank 3 amd 4 opening until you catch up.
