### ISSUE TITLE
dupla támadás bolygó ellen

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1118]
ha ugyanazt a bolygót támadjuk egy AIval (esetleg szövetségessel), miután én elfoglaltam azt, Ő nem korrigálja a flottáját és automatikusan csata lesz, ha szövik ha nem, természetesen egyből háború és kapcsolatromlás. 

ha Ő foglalja el elöbb, akkor az én flottám sem áll meg automatikusan

**Comment by akarnokd** [comment]
Should be fixed via *v0.95.245*.
Remélhetőleg javítva a *v0.95.245*-tel.
