### ISSUE TITLE
földi csata AI

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1121]
földi csatában tankokat utasitom hogy romboljanak le egy épületet. amig odaérnek addig távolabbról is lönek. DE amikor közel érnek és félkör alakban körbevesznek valami nagyobb épületett akkor csak az első sorban lévő tankok tüzelnek, aki hátrább van az semmit nem csinál

**Comment by hemoridos** [comment]
Köszi a tesztet! Sikerült reprodukálni. Van elképzelésem mi lehet a baja. A tank próbálna közelebb menni de nem talál utat/blokkolva van a kitalált útja egyéb okokból, ezért x próbálkozás után feladja ás megáll.


Most könyékig benne vagyok egy nagyobb funkcióban, amíg azzal nem végzek nem igérek erre javítást.

**Comment by akarnokd** [comment]
> Most könyékig benne vagyok egy nagyobb funkcióban, amíg azzal nem végzek nem igérek erre javítást.

Min dolgozol, ha szabad érdeklődni?

**Comment by hemoridos** [comment]
Űrharc útkeresést kezdtem el összerakni, csak a vizsgaidőszak kicsit megakaszott.

**Comment by akarnokd** [comment]
> Űrharc útkeresést kezdtem el összerakni, csak a vizsgaidőszak kicsit megakaszott.

Ettől tartottam.

Azért nem foglalkoztam vele annó, mert kínszenvedés tutujgatni a kis-nagy hajókat egyenként. Kerülgetnék egymást, forognak körbe-körbe, blokkolják egymást, közben a védelem meg egyenként ledarálja őket. A szabad forma nem szép, de kényelmes.

Úgyhogy remélem, hogy minimum kapcsolható lesz, vagy rétegelt (kis-közepes-nagy külön rétegen mozog, így nem űtköznek annyit).

**Comment by hemoridos** [comment]
Igen, ezek a problémák bennem is felmerültek. Hosszabb távon a rétegelt tűnik számomra a legcsinosabb megoldásnak, de végül úgy gondoltam első körben megpróbálok hű maradni az eredetihez kipróbálni hogy nézne ki open-ig-ben.
Ha megvan egy alap azon már tudok iterálgatni pl.:
 - növelni a gridet hogy jobban jobban elférjenek
 - mindenki 1x1-es méretű legyen
 - rétegelni
 
 De mindenképp rakok rá kapcsolót.
