### ISSUE TITLE
Vírushordozók

### ISSUE THREAD

**Issue by Pistapapa** [akarnokd/open-ig#1127]
Ha a vírushordozókat automatikus harcban győzőm le nem pipálja ki a küldetést és nem tudok szintet lépni. Normál csatában nincs gond.
[virus.zip](https://github.com/akarnokd/open-ig/files/14798092/virus.zip)

**Comment by akarnokd** [comment]
Javítva: https://github.com/akarnokd/open-ig/commit/2b5cf28cca29e913bd0b691e7a3a7d8b719c5b7b
