### ISSUE TITLE
Dribs szövetséges támadása

### ISSUE THREAD

**Issue by Pistapapa** [akarnokd/open-ig#1129]
Volt egy olyan szituáció, hogy katonai szövetségben voltam Dribs-ekkel és egy olyan Dargslan bolygó felé indított támadást, amit én közben elfoglaltam míg ők a térkép másik végéből úton voltak. Annak ellenére, hogy már az enyém volt, így is megtámadta és rögtön bomlott is a szövetség. :)

Amúgy ezt már akartam kérdezni, van olyan szövetség is aminél nem valami ellen kötjük a szövetséget, csak a jó viszony miatt felajánlja. Akkor viszont nem kapcsolódnak össze a radarok. Ez direkt van így? 

Most egy pár dolog eszembe jutott még. Úgy rémlik, hogy az eredetiben Park-ot nem lehetett jeges bolygóra tenni. 

A nehéz játékmódot rendkívül megkönnyíti eleinte a Feketepiac, talán ki lehetne kapcsolni az első néhány szinten amíg nem lehet gyártani.

**Comment by FaLiar** [comment]
ez visszatérő bug, hogy az AI nem vizsgálja felül a bolygot ami felé egyszer elindul... irtam énis róla többször

**Comment by akarnokd** [comment]
Should be fixed via *v0.95.245*.
Remélhetőleg javítva a *v0.95.245*-tel.
