### ISSUE TITLE
Errors in the campaign and colony control panel

### ISSUE THREAD

**Issue by KZK07** [akarnokd/open-ig#1133]
Hello,

I'm uploading game saves for errors in the planet's control panel and errors when opening the "Gummp" campaign.

[save-2024-04-22-19-03-14-207.xml.gz](https://github.com/akarnokd/open-ig/files/15068662/save-2024-04-22-19-03-14-207.xml.gz)
[save-2024-04-22-18-59-40-808.xml.gz](https://github.com/akarnokd/open-ig/files/15068666/save-2024-04-22-18-59-40-808.xml.gz)
[save-2024-04-18-18-06-24-688.xml.gz](https://github.com/akarnokd/open-ig/files/15068667/save-2024-04-18-18-06-24-688.xml.gz)
[save-2024-04-21-11-38-04-453.xml.gz](https://github.com/akarnokd/open-ig/files/15068671/save-2024-04-21-11-38-04-453.xml.gz)
[save-2024-04-21-11-31-51-755.xml.gz](https://github.com/akarnokd/open-ig/files/15068673/save-2024-04-21-11-31-51-755.xml.gz)
[save-2024-04-19-12-33-42-537.xml.gz](https://github.com/akarnokd/open-ig/files/15068676/save-2024-04-19-12-33-42-537.xml.gz)
[save-2024-04-18-18-06-24-688.xml.gz](https://github.com/akarnokd/open-ig/files/15068678/save-2024-04-18-18-06-24-688.xml.gz)
[save-2024-04-18-18-05-36-463.xml.gz](https://github.com/akarnokd/open-ig/files/15068683/save-2024-04-18-18-05-36-463.xml.gz)

This is my first post on this forum. I'm not sure if I sent the files correctly. If I sent something incorrectly, please let me know.
Regards
Marcin

**Comment by KZK07** [comment]
I'm glad I could help, if I find any more errors I will send them to you.
I've been coming back to IG for 20 years and I'm glad the project is still
evolving.
See you soon!

pon., 22 kwi 2024 o 23:34 David Karnok ***@***.***>
napisał(a):

**Comment by akarnokd** [comment]
Okay, I know what happened. We introduced custom building images which changed the building footprints. In your case, alien church has a different footprint and breaks the rendering.

If you are not that attached to that playthrough, I recommend starting a new skirmish game.

**Comment by akarnokd** [comment]
Crash fixed via *v0.95.245*. But the render may still look wrong due to potentially overlapping and clipping buildings. Please rebuild these buildings.

**Comment by KZK07** [comment]
Hello,

I checked and the error disappeared so it must have been what you're
talking about. Thanks. If I find any more errors, I will send them to you.

Regards
Marcin

wt., 23 kwi 2024, 10:00 użytkownik David Karnok ***@***.***>
napisał:
