### ISSUE TITLE
Space battle projectors missing projectiles(?)

### ISSUE THREAD

**Issue by hemoridos** [akarnokd/open-ig#1145]
I noticed that in original IG the planetary guns fire 2 types of projectiles(One their own and one from a level below ie. Ion guns fire Ion projectiles, Plasma guns fire one plasma and one ion projectile etc.)
In open IG there is only one projectile for each gun. Is this deviation intended? It does make sense to IMO but still curious.

Alternatively maybe we could have 2 projectiles with the double barreled guns with half the damage each.

Also I noticed that guns don't use weapon ports but have the projectile's properties set in their configuration. Is there any specific idea behind this?

**Comment by akarnokd** [comment]
Didn't want to complicate the models. What mattered is the damage, not the virsuals.

**Comment by akarnokd** [comment]
I don't know.

**Comment by hemoridos** [comment]
I'll leave it as is. I can work around this for now.
