### ISSUE TITLE
stuck after Garthog Fleet attacked 

### ISSUE THREAD

**Issue by highfly117** [akarnokd/open-ig#1156]
The Campaign seem stuck at the point where the Garthog attempted to attack one of your planets after your promoted the first time nothing happens any more I have two objectives to perform.

. Try to build at least one Barracks 

. Build Factories and try constructing ships and Equipment.

Nether of these change even though I have don't them both. Nothing happens after this now and to be specific the Garthog did land and i then i beat them.

[save-2024-07-15-23-37-55-239.xml.gz](https://github.com/user-attachments/files/16241085/save-2024-07-15-23-37-55-239.xml.gz)

**Comment by akarnokd** [comment]
Those are general objectives, they don't complete until the story progresses to a certain point.

**Comment by highfly117** [comment]
I fixed it by using the debug menu and completing and restarting mission 11
