### ISSUE TITLE
Battleships spawning in top left of space battle map

### ISSUE THREAD

**Issue by highfly117** [akarnokd/open-ig#1157]
For some reason all battleships the players or alien race spawn in the top left of the space battle map, attached a screenshot to show

![image](https://github.com/user-attachments/assets/24e478a2-2637-44de-8d5a-b2b7ae8fdd6d)

None of the formations change where the battleships are or where they spawn they are always in the top left

**Comment by hemoridos** [comment]
Some of the assets were changed, that specify the where battleships should be placed.
Deleting the file open-ig-images-<someSpecificDate>.zip and running Verify in the launcher should solve it.

**Comment by highfly117** [comment]
I have done as you said and deleted open-ig-images-20240607a.zip from the main game directory. Then ran the launcher and verified the installation which then detects the missing files re-downloads them. but in my latest save i get the same issue as above. Will i need to start a new game to fix the issue?
  

![image](https://github.com/user-attachments/assets/c520e319-9ad8-4e3b-8279-791644337788)

**Comment by akarnokd** [comment]
Please delete all subdirectories except *save*:

![image](https://github.com/user-attachments/assets/6bbcee6c-7bdd-4445-9bd0-7ce7bb8c04a6)

**Comment by highfly117** [comment]
Cheers dude, That solved it
