### ISSUE TITLE
Destroyer 2 not avaible after Prototype

### ISSUE THREAD

**Issue by TheBenn** [akarnokd/open-ig#1158]
After finishing the Prototype Mission, I am not granted a Destroyer 2 nor can I produce or research it.
My save directory: [save.zip](https://github.com/user-attachments/files/16442736/save.zip)
There is a save named "Prot" right at the start of the mission.

Any help is much appreaciated, thanks :)

**Comment by hemoridos** [comment]
Which version are you playing on?

I tried your saves both Prot Done and Prot.
In Prot Done the destroyer 2 was already researched and buildable.
In Prot If I managed to save the ship in the Garthog attack, I got the same result, Destroyer 2 researched and buildable. However if  the prototype got destroyed in the battle, I got the results you mentioned no destroyed 2 research and no pulse laser.

**Comment by TheBenn** [comment]
I am on version 0.95.248, the lastest the launcher installed for me.
It should just appear in the production tab the same way as fighter 1 and 2, right?

**Comment by hemoridos** [comment]
Yes

This is what I see when playing the "Prot done" save
![image](https://github.com/user-attachments/assets/2f4c7842-0f49-4c0e-8f15-bd90d3f26331)

**Comment by TheBenn** [comment]
Ah my bad, I never actually used the production screen itself and just used the little cog symbol at the top right, where it doesn't appear. Thank you so much.

**Comment by hemoridos** [comment]
That's fine. That sounds like a bug.

**Comment by akarnokd** [comment]
Thanks for the feedback. We'll release an update shortly.

**Comment by akarnokd** [comment]
Resolved in https://github.com/akarnokd/open-ig/commit/436e9c7b1f75e6d6411080366c98b148a8ebbc13
