### ISSUE TITLE
MI-kolónia irányítás

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1162]
Kíváncsiságból pár bolygó kezelését rábíztam az MI-re.
Az egyik bolygón ez a jelenlegi eredmény, ami a képen látszik. :)
![MI kolonia](https://github.com/user-attachments/assets/4ea6d26f-3657-487d-a4fa-6e9e7976e9e6)

**Comment by akarnokd** [comment]
Feltöltenéd a mentést is?

**Comment by hemoridos** [comment]
A szokatlanul sok rendőrség problémával már találkoztam, de ennyivel még nem.
Hétfőn belenézek.

**Comment by akarnokd** [comment]
A letiltott meglévő épületek okoznak zavart. Dolgozom rajta, de a javítás ellenőrzéséhez mindenképpen kellene a mentés.

**Comment by G-T-T-G** [comment]
Megkeresem melyik ez a mentés, és küldöm. Azóta leromboltam mindet, és kikapcsoltam az MI-t, így vissza kell keresnem.

**Comment by akarnokd** [comment]
Történt némi javítás ebben a témában a v0.95.251-gyel. Ha még mindig fennáll a hiba, kérlek nyisd újra ezt az issuet.

**Comment by G-T-T-G** [comment]
Előkerestem a mentést.
Azóta nem próbálkoztam vele, úgy játszottam végig, hogy kikapcsoltam az MI-t azokon a bolygókon ahol megengedtem neki.
Ezért hagyd majd lezárva a témát.

[save-2024-08-24-22-45-09-404.xml.gz](https://github.com/user-attachments/files/16737970/save-2024-08-24-22-45-09-404.xml.gz)
