### ISSUE TITLE
Űrharc esetén nem védekeznek az egységek maguktól

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1164]
Sziasztok,

Űrharc esetén, legyen szó Flotta - Bolygóvédelemről, vagy Flotta - Flotta harcról, a saját egységek nem kezdenek el védekezni anélkül, hogy egyetlen ellenséges célpontot ki nem jelölnék, és meg nem támadnék. Rakétázás esetén sem indul el a védelmi támadás, annak ellenére, hogy a lőtávon belülre ér az ellenséges egység.
Köszi :)

![Űrharc nem védekeznek](https://github.com/user-attachments/assets/1fecc4ed-f7f6-4cfb-9049-d23bfc767622)
![Űrharc nem védekeznek2](https://github.com/user-attachments/assets/b205c2c0-3a7e-40ad-9e62-5a6fa82441f7)
![Űrharc nem védekeznek3](https://github.com/user-attachments/assets/989d699f-4706-404a-9588-8854749f6bb3)

[save-2024-08-28-23-10-59-049.xml.gz](https://github.com/user-attachments/files/16788985/save-2024-08-28-23-10-59-049.xml.gz)

**Comment by akarnokd** [comment]
Manuálisan őrzés módba kell kapcsolnod az egységeket.

Ez azért van, mert különben mindent megtámadnának a kampány során, amit nem kellene bántaniuk, mert csevegéssel is lehet rájuk hatni.

**Comment by G-T-T-G** [comment]
Rendben, köszi :)
CD-s változatban nem volt ezzel gond, ezért jeleztem.

Másik amit észrevettem, hogy a Hajók, vagy Bolygók felszerelésekor, ha valamilyen tartozékból nincs kellő mennyiség legyártva, vagy abszolút nulla pl egy fegyver, rakéta, stb, amiből több kell egy hajóra, és a +++ ikont megnyomva, fejleszted/felszereled az egységeket, akkor mondjuk 25cirkáló esetén az első 12őt fullra pakolja, az utolsó 13at, meg lekopasztja nullára.

**Comment by akarnokd** [comment]
> Másik amit észrevettem

Kérlek, különálló problémákat külön issue-ban jelezd.
