### ISSUE TITLE
Eltűntek a feliratok, Bolygónevek, Flottanevek

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1165]
Sziasztok,

Egyik pillanatról a másikra eltűntek a feliratok, a Csillagtérképről.
Megnyitottam valamelyik Kolóniát, és a Térképre visszatéréskor már nem voltak feliratok.
Ellenőriztem a beállításokat, Újraindítottam a Játékot mentésből, majd a programot is, és nem állt vissza.

![Feliratok](https://github.com/user-attachments/assets/c0596815-4143-4d9c-8bd6-b86961b36467)

[save-2024-08-29-22-20-46-385.xml.gz](https://github.com/user-attachments/files/16805582/save-2024-08-29-22-20-46-385.xml.gz)

**Comment by akarnokd** [comment]
![image](https://github.com/user-attachments/assets/705602e7-d761-4629-b954-ac400af5ac21)

**Comment by G-T-T-G** [comment]
Óistenem.....
Nézdd el nekem 3napja alig alszom, egy komoly auditra készülünk, és egész nap kiég a szemem az Excel tábláktól...
Többek közt ezért is futtatom a játékot minden este, éjjel, vagy munkakezdés előtt, hogy egy kicsit lelazuljon az agyam...
Sorry :(
