### ISSUE TITLE
Auto-építés, kényelmi funkció

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1167]
Sziasztok,

Ezek közé a beállítások közé be tudnátok tenni azt a lehetőséget, hogy a bolygók "Auto-építése" és ugyanazok a választási lehetőségek mint amik Bolygóinfónál választhatóak.
Ennek azért látnám értelmét, mert minden Kolonizálás, vagy Bolygómeghódítás után, be kell állítanom az Auto-építést, ha használom az MI felügyeletet (Ami iszonyatosan jó let!!!), vagy bármilyen más Auto-építést.

![image](https://github.com/user-attachments/assets/70d86f1f-76a3-4319-9ed6-a0c63cedbcff)

**Comment by akarnokd** [comment]
Implementálva: #1175
