### ISSUE TITLE
MI-kolónia irányítás 2.

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1169]
Sziasztok,
Az MI felügyelt bolygókon a Lakóépületeket, Naperőműveket, Fúzióserőműveket, Kórházat, Rendőrséget nem fejleszti az AI, hanem legtöbbször csak épít még egyet, Lakóépületet szinte sosem épít. Lehet hogy ez összefüggésben van a korábbi javítással amit korábban jeleztem? #1162

![image](https://github.com/user-attachments/assets/570d19df-8181-4bb8-b6c9-6974b0126526)

**Comment by akarnokd** [comment]
Az AI akkor fejleszt, ha már nem tud hova építeni.

**Comment by G-T-T-G** [comment]
Rendben, akkor ez nem hiba. :)
