### ISSUE TITLE
Upscale - nagyfelbontású vagy részletességű, modern sprite-ok

### ISSUE THREAD

**Issue by deejayy** [akarnokd/open-ig#1173]
Játszottam egy kicsit valami egyszerű stable diffusion-nel, hogy feljavítsam a standard sprite-ok minőségét. Sajnos a felbontás növelésével az épületek alapterülete is nagyobb lett :) túl nagy különbségnél pedig triggereltem a fájlellenőrzőt. Viszont ha visszakicsinyítettem, akkor már lett némi értékelhető eredménye.

régi vs. új
![image](https://github.com/user-attachments/assets/46dc1660-034b-4fc1-80d3-ddfd4e93982e)

![image](https://github.com/user-attachments/assets/f4259884-f346-4b77-a853-7e753f66c0fc)

Vannak artifact-ek, de csak mert béna voltam és összecsaptam.

Van/lesz lehetőség arra, hogy részletesebb és nagyobb felbontású sprite-ok nem eredményeznek játékbeli kiterjedés növekedést is?

**Comment by akarnokd** [comment]
Köszi, de nem szeretnék hozzányúlni az eredeti grafikához. Nem olyan rossz minőségű és van neki egy nosztalgikus bája.

**Comment by deejayy** [comment]
Abszolút egyetértek, a dolog, ami miatt eszembe jutott, az a zoomolás. Mivel most lehet nagyobb, mint 1x-re zoomolni, ott már az eredeti képek pixelesek. Upscale-lel ezen lehetne javítani.
