### ISSUE TITLE
Mission: Szállító kísérete nem ér véget

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1178]
Sziasztok,

Az utolsó frissítés után egy módosított főkampány keretében indítottam egy Hadjáratot Nehéz szinten.
A "Szállító kísérete" küldetés a Szállító flotta Centronomra érkezése után nem tűnik el, a játékmenet megáll, végtelenségig játszható az adott szinten.
Érdekesség, hogy a szállító felszerelését meg lehet nézni, arra gondolok, nem-e az új feature okozza a problémát, a kis infokijelző, hogy a maximális felszereléshez gyártandó cuccokat kilistázza.
Mellékeltem a mentést, és Screen-t.
(Eddig a módosított Kampányok esetén nem ütköztem problémába, ami volt azok kisebb elírások voltak a battle; tech; fájlokban, amiket sikerült is javítanom.)

![Transporter mission never ending](https://github.com/user-attachments/assets/7a85ba72-d8f4-4bc7-89e9-d6ef0a6f08e6)
![Transporter mission never ending2](https://github.com/user-attachments/assets/a6cfa2fa-ddf0-47ad-a33b-b21769fc51df)

[save-2024-10-01-20-01-02-227.xml.gz](https://github.com/user-attachments/files/17214086/save-2024-10-01-20-01-02-227.xml.gz)

**Comment by akarnokd** [comment]
A kampányfájlok nélkül meg sem tudom nyitni a mentést. Elvileg a legutóbbi módosításoknak nincs hatása a küldetésekre.

**Comment by G-T-T-G** [comment]
Küldöm

[GT.zip](https://github.com/user-attachments/files/17214478/GT.zip)

**Comment by akarnokd** [comment]
Valószínűleg a flotta túl gyorsan ment, így elsuhant a San Sterling mellett, és nem indította el a támadást.

Ezt a hibaállapotot nem tudom javítani, vissza kell töltened a küldetés előtti mentést, és lassúra venni a hajómozgást.

**Comment by G-T-T-G** [comment]
Megvolt a Kalóztámadás, le is győztem.
Én is pillanatnyi hibára gyanakodtam, újraindítottam az egész küldetést a kezdőmentésről, ezt küldtem el, újra ugyanott állt meg.

Elküldöm mindegyik mentést, a mai napról.

[GT1001.zip](https://github.com/user-attachments/files/17215208/GT1001.zip)

Próbaképp elindítok egy alap eredeti kampányt gyorsan, megnézem ott mi lesz.

**Comment by G-T-T-G** [comment]
A sima főkampányban minden rendben. Továbblépett.
Szerintem tudod mi lesz a baj? A korlátozó terület a Főkampányban sokkal kisebb, mint az általam készítettben, Mindjárt megpróbálom a Script fájlt módosítani és úgy elindítani.

**Comment by akarnokd** [comment]
Most már látom, mi a gond. Megváltozott a látható terület és emiatt nem fejeződik be a küldetés rendesen. Alapból a Centronom nem elérhető.
Meglátom, hogy javítható-e.

**Comment by akarnokd** [comment]
Javítottam a 0.95.257-ben. Kérlek ellenőrizd, hogy működik-e. Nem kell újrakezdeni a küldetést, az eredeti mentés is meg kell, hogy javuljon.

**Comment by G-T-T-G** [comment]
Közben én is próbálkoztam a terület kijelöléssel, és a csökkentése, a Centronom alá megoldotta.

Ennél nem mehet magasabbra, és balra.
<limit-views>
    <?limit-view id='Empire.Level.1' inner='' outer='225, 400, 120, 80'/?> Eredeti
    <limit-view id='Empire.Level.1' inner='' outer='210, 390, 200, 130'/> Új itt ha ez szerepelt az zavarta meg: '180, 360, 200, 130'
    <limit-view id='Empire.Level.2' inner='' outer='180, 360, 200, 130'/>
    <limit-view id='Empire.Level.3' inner='' outer='150, 360, 300, 130'/>

**Comment by G-T-T-G** [comment]
A javításod is megoldotta egyből :)
Köszi 👍  Szuperek vagytok.

![image](https://github.com/user-attachments/assets/71400c1f-255a-407f-bae2-138cd79a40e6)
