### ISSUE TITLE
A diplomácia ablak nem működik

### ISSUE THREAD

**Issue by CsoGee** [akarnokd/open-ig#1184]
Szia!
Ahogy írtam FB-n. A diplomácia ablak csak az első lehetősénél (az 5.szint elején) aktív. Utána hiába megyek rá a diplomácia szobára (még akkor is, ha látom hogy kaptam üzenetet), a diplomácia már nem lesz aktív. Az üzenetablak megnyílik, az üzenetet megkapom, de reagálni már nem tudok rá és utána szürke marad a faj neve, így nem tudok beszélgetést kezdeményezni. Aztán rájöttem, hogy ha lementem a játékot és kilépek, akkor a következő játékindításnál és betöltésnél még mindig szürke marad a diplomácia, de a kapott üzenetre végre tudok reagálni és akkor megnyílinak a lehetőségek is a beszélgetésre, így egy fajjal tudok tárgyalni. Ezután újra mentek, majd újra kilépek a játékból, majd belépek, betöltök és a másik faj üzenetét elolvasva, azzal is tudok tárgyalni. Aztán mentés, kilépés, belépés, betöltés és következik az újabb faj. Kicsit megterhelő... :) Meg tudnád nézni, hogy mi lehet a probléma? Feltöltöttem a mentési fájlt.
Előre is köszi!
CsoGe
[save-2024-11-03-16-46-40-455.xml.gz](https://github.com/user-attachments/files/17611063/save-2024-11-03-16-46-40-455.xml.gz)

**Comment by akarnokd** [comment]
Javítva a v0.95.260-ban. Kérlek ellenőrizd.

**Comment by CsoGee** [comment]
Ez gyors volt! :)
Este megnézem, köszi!

David Karnok ***@***.***> (időpont: 2024. nov. 3., V, 17:24)
ezt írta:

**Comment by CsoGee** [comment]
Tökéletesen működik, köszönöm! :)

Gergely Csoltó ***@***.***> ezt írta (időpont: 2024. nov. 3.,
V, 18:02):
