### ISSUE TITLE
Spacewar: overlapping units

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akarnokd/open-ig#122]
```
Add pathfinding options to the spacewar screen and ensure units will not 
overlap.

The spacewar screen is more difficult as units have different sizes and move on 
a high-resolution coordinate system.
```

Original issue reported on code.google.com by `akarn...@gmail.com` on 30 Oct 2011 at 11:03

**Comment by akarnokd** [comment]
After long-long deliberation, I won't add this. Spacewar would become super clumsy with ships trying to avoid each other and seemingly ignoring user commands.
