### ISSUE TITLE
havi összesítő

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akarnokd/open-ig#782]
```
Game version:0.95.151

A régi IG -ben volt egy napi bevételösszesítő/morálösszesítő kis ablak 
nap végén, ami innen hiányzik, pedig nagyon hasznos volt, jó volna ha a 
java verzióban is lenne...
```

Original issue reported on code.google.com by `laci8...@gmail.com` on 1 Oct 2013 at 2:10

**Comment by akarnokd** [comment]
Úgy döntöttem, nem implementálom. Megtöri a játékmenetet és érdemben nem ad információt, mivel a napi szintű haladás sokkal értékesebb információ.
