### ISSUE TITLE
Feature request: More than five entries on factory screen

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akarnokd/open-ig#809]
```
Sometimes the five slot on the factory screen is not enough. The capacity is 
divided anyway, so i think there is place for more slots.
```

Original issue reported on code.google.com by `kli...@gmail.com` on 18 Jan 2014 at 1:01

**Comment by akarnokd** [comment]
The 5 slot limit also there as a gameplay feature, requiring the player to manage and decide what to produce and when.
