### ISSUE TITLE
Background music in campaign

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akarnokd/open-ig#900]
```
Game version: 0.95.199

It's a very small issue, but the original game's background music, which as far 
as I know has two tracks, is already looping both tracks from the start, while 
this should be only the first track for the lower ranks. From either Admiral or 
Grand Admiral only the second track should be looped.

Operating System: Windows 7 64-bit

Java runtime version: 1.7.0_71

Installed using the Launcher? yes

Game language: EN
```

Original issue reported on code.google.com by `MFHout...@gmail.com` on 5 Nov 2014 at 10:07

**Comment by akarnokd** [comment]
When I first included the music, I was surprised I never heard the 3rd music before. Probably because of what the OP said about limiting the music to ranks. I don't see any reason to hide the music behind progression as by themselves, all of them are great to listen to at any point in time.
