### ISSUE TITLE
AI Stocking space stations with Greater than max missles

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akarnokd/open-ig#915]
```
Game version:0.95.203


Operating System: Windows 7 x64 SP1 


Java runtime version: 1.8.0_20


Installed using the Launcher? yes


Game language (en):


What steps will reproduce the problem?
1.Set Own Planets to AI Managed
2.
3.


What is the expected output? What do you see instead?
Expect AI to only stock space stations with MAX missles.
AI Actualy stocks space stations with hundreds of missles


Please provide any additional information below.


Please upload any save before and/or after the problem happened. Please
attach the open-ig.log file found in the
application's directory.

```

Original issue reported on code.google.com by `jims.par...@gmail.com` on 24 Jan 2015 at 5:23

Attachments:
- [info-2015-01-24-16-22-11-429.xml](https://storage.googleapis.com/google-code-attachments/open-ig/issue-915/comment-0/info-2015-01-24-16-22-11-429.xml)
- [save-2015-01-24-16-22-11-429.xml.gz](https://storage.googleapis.com/google-code-attachments/open-ig/issue-915/comment-0/save-2015-01-24-16-22-11-429.xml.gz)

**Comment by hemoridos** [comment]
This issue is resolved in e73e629839b99d230b66f310b134c4e03bb65cca
