### ISSUE TITLE
Destroying a colony doesn't work

### ISSUE THREAD

**Issue by anonymissimus** [akarnokd/open-ig#921]
When a planet's population reaches zero, the colony should vanish (it used to). Instead, it remains with 0 population and tax calculation is severely broken. It has to do with continuous moral/tax calculation, it must be active.
Outer 15 is almost gone: http://www.mediafire.com/download/839uc2bc1b8ztft/save.zip

**Comment by akarnokd** [comment]
Thanks. Fixed via [this commit](https://github.com/akarnokd/open-ig/commit/db4f5a5cee14c27892ba570fb8c1093d4bcfa3e8).
