### ISSUE TITLE
Új profil, folytatás

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#922]
Ha létrehozok egy új profilt és rányomok a folytatás gombra, akkor:

===
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.7.0_75
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Linux, amd64, 3.16.0-4-amd64
   Game version: 0.95.204
   Command line: [-memonce, -hu]
   Available memory: 78 MB
   Maximum memory: 739 MB
   Parallelism: 4
   Language: hu
   Date and time: 2015-03-25T11:53:10.172Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
No saves!

===
Szerintem, ha nem lehet folytatni, akkor ki lehetne szürkíteni a gombot.

**Comment by akarnokd** [comment]
Kösz. Javítva: https://github.com/akarnokd/open-ig/commit/b3e9f277562f4a7da278704e2ddd15bb417829b6 .
