### ISSUE TITLE
San Sterling: Nem lehet szólni a kereskedőknek a blokádról!

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#924]
Amikor a San Sterlingre cigit csempésznek, a vörösen villogó (a bolygóra tartó) kereskedőket hiába kapom el, nem tudom mondani nekik, hogy blokád alatt a bolygó, csak továbbengedni vagy fenyegetni tudom őket ("Lőgyakorlatot tartunk", "Fel kéne melegítenem a fegyvereimet", stb.)

**Comment by akarnokd** [comment]
Ha a kereskedő nem a San Sterling-re tart, akkor nem kapod meg a blokádos üzeneteket.

**Comment by feqolosi** [comment]
Csak hogy oda tartott! Miután futni hagytam, leszállt a bolygón! Egyébként a San Sterlingi blokádnál nem villog vörös keret sem a bolygó felé tartó kereskedőkön.

**Comment by akarnokd** [comment]
Tudnál küldeni mentést?

**Comment by feqolosi** [comment]
Hu-ha, sajnos már nem. Az automentés csak egy hétig nyúlik vissza, azonkívül a szintkezdések vannak csak. Szintkezdés is jó? Melyik szint is ez, 1. vagy a 2.?

**Comment by akarnokd** [comment]
Küldheted az akarnokd at gmail dot com címre.

**Comment by sonofEU** [comment]
Rendben. Melyik filet szedjem ki?

**Comment by akarnokd** [comment]
Küldd el a xml.gz fájlokat, nem kell kitömöríteni.

**Comment by sonofEU** [comment]
Elment.

**Comment by akarnokd** [comment]
Kösz, így már megvan a hiba oka. Javítva: https://github.com/akarnokd/open-ig/commit/2abb7374a9ca3b51aed19802cf5bd68f7b936b8e
