### ISSUE TITLE
Vörös kereten kívül duplaklikk

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#925]
Az első két szinten a körzethatáron (vörös keret) kívül látszik a Garthog 5 és egy db flotta felette. Szimpla klikkel nem lehet őket kijelölni, de duplaklikkel kinyitja a felszerelést és a kolóniát és utána, ha visszamászok a térképre, akkor már ki van jelölve.

**Comment by akarnokd** [comment]
Köszönöm.

**Comment by akarnokd** [comment]
Ezt a hibát nem tudom reprodukálni, lehet, hogy javítva lett valamivel együtt.
