### ISSUE TITLE
Zeuson kormányzója kinyiffant, mission failed?

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#926]
Az előbb véletlenül rakétákkal kinyírtam a Zeuson bolygó kormányzóját, de még előtte megfutamodott, a két vadásza meg is lépett, viszont a gép úgy értékelte, hogy nem sikerült megállítani.

**Comment by Markus79** [comment]
Mert bíróságra kell szállítani az a feladat, az nem sikerült. Ez nem bug.

**Comment by akarnokd** [comment]
Nem vagyok 100%-ban biztos, de valóban vagy lebeszéled, vagy kicsit leamortizálod a kormányzó flottáját, de nem szabad megölni.
