### ISSUE TITLE
Földi harc: útvonalkeresési mizériák tömkelege

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#929]
A tankok útvonalkeresése enyhén szólva is nagyon bugos, néha feltornyosulnak egymás mögött és megállnak. De ami nagyobb baj, hogy ilyenkor a parancsnak sem engedelmeskednek! Hiába adok más parancsot, addig ott állnak, amíg ki nem lőnek egy párat közülük. Az is vicces, amikor mondom nekik, hogy lőjenek mondjuk a laktanyára és ha útba van pár ellenséges tank, akkor nekiállnak megkerülni a fél világot. Akkor is, ha elakadnak valahol, akkor lebénulnak. Igazából, ha bárhol elakadnak, akkor lefagynak és nem lőnek, nem mozognak, nem reagálnak.

**Comment by akarnokd** [comment]
Sajnos ez régóta fennáll. Vagy kis csoportokban küldöd őket támadni, vagy használod a CTRL+Jobb kattintást a földön, és akkor minden útjukba eső ellenséget támadnak útközben.

**Comment by feqolosi** [comment]
Értem, köszönöm a tippet.

Mi a probléma pontosan, ami miatt ez még nem került javításra?

**Comment by hemoridos** [comment]
This has been resolved.
