### ISSUE TITLE
Pattra végződő földi harc.

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#930]
A játék néha bevágja a támadó ellenfél tankjait a sarokban előforduló hegyek, szakadékok mögé és onnan nem tudnak kijönni; én meg bemenni nem tudok: patthelyzet, senki nem nyeri meg a csatát, lehet betölteni az utolsó mentett állást.

**Comment by TCH68k** [comment]
[https://github.com/akarnokd/open-ig/issues/730](A 730-as hiba ugyanez, nem?)

**Comment by akarnokd** [comment]
Valóban.
