### ISSUE TITLE
Űrcsata: a pálya széle vajon mí? :)

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#932]
Az űrcsatában ki lehet menni a pályáról! Kizoomolok és kimegyek a sötétbe! És az ellenfél nem vesz észre addig, amíg vissza nem jövök! Igaz, hogy onnan "kintről" lőni sem lehet (a lövések hangja hallatszik, de lövés nincs), de hátbatámadni az ellenséget lehet. Simán bementem a bolygó mögé és hátulról támadtam...a "felszínről"! :P

**Comment by hemoridos** [comment]
This has been resolved.
