### ISSUE TITLE
Zene: új trackek lejátszása néha elmarad.

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#933]
A zene néha csak úgy elhallgat, miután befejezte valamelyik track lejátszását. Nincs hiba és a hangeffektek is megvannak, csak a zene állt meg. Aztán egyszercsak visszajön.

**Comment by feqolosi** [comment]
Pedig kihajítottam a pulseaudiot. Vagy Linux alatt maga a Java az, aminek ennyire gyehenna a sound backendje?

**Comment by akarnokd** [comment]
Bezárom, mert régi a diszkusszió és azóta több Java és Linux verzió kijött már.
