### ISSUE TITLE
Fontos eseménynél nincs autopause, vagy legalább autoslowest

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#934]
Az eredeti játékban amikor ellenséges flotta közelített valamelyik bolygómhoz, akkor a játék egyesbe vágta a sebváltót, itt viszont a sebesség megmarad: néha egyszerűen nincs időm reagálni, felharsan a másodtiszt alarmja és már le is rohantak...

**Comment by akarnokd** [comment]
Az játék beállítások között van opció a lassítás bekapcsolására idegen támadás esetére.

**Comment by feqolosi** [comment]
My bad, sorry.

**Comment by feqolosi** [comment]
Hoppá, de most nézem, hogy ez be van kapcsolva! Mégsem lassította le, ellenséges támadáskor!

**Comment by akarnokd** [comment]
Van valami mentésed, ahol ez történik?

**Comment by feqolosi** [comment]
Minden mentésemben így történik. Ez az opció nem globális, azaz mentéstől független?

**Comment by akarnokd** [comment]
Ez mentéshez kapcsolódik, így ha váltogatsz a mentések között, akkor akár ki is kapcsolhat.

**Comment by feqolosi** [comment]
Na, akkor erre majd ügyelek.
