### ISSUE TITLE
Parancsnoki hídon a framerate nagyon alacsony.

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#939]
Be van lassulva minden, a kivetítőt is lassított felvételben engedi le. A videólejátszás sebessége normális, csak maga a parancsnoki híd van belassulva.

**Comment by akarnokd** [comment]
A híd animációk fix framerate-tel működnek, általában 10-17 és a hanghatások idejéhez van szinkronizálva.

**Comment by feqolosi** [comment]
Huh, pedig DOS-ban ez 2-3x gyorsabb volt. Lehet, hogy az volt bugos? :) (Ha jól emlékszem 486-osra írták a játékot és a sokkal gyorsabb superscalar 586-on egy rakás bug előjött.)
Tényleg, most nálad a játék forrkódja. Tényleg Pascalban írták, ahogy pár éve a RLE videó visszafejtése közben gondoltad?

**Comment by akarnokd** [comment]
Talán Borland C++, nem tudtam megkülönböztetni.

**Comment by feqolosi** [comment]
A C++-t meg a Pascalt?
Ha kapcsos zárójelek vannak benne, akkor C/C++, ha begin/end párosok, akkor Pascal.

**Comment by akarnokd** [comment]
Az eredetinek nincs meg a forráskódja, csak a lefordított bináris mutat olyan jegyeket, amilyeneket egy Borland fordító szokott beletenni.
