### ISSUE TITLE
thanks and question

### ISSUE THREAD

**Issue by akontalev** [akarnokd/open-ig#945]
Thank you for your work , for the opportunity to enjoy a cosmic masterpiece.
I have a question - often during ground battles , I can not speed up the battle. What could be the problem?

**Comment by akarnokd** [comment]
Have you tried clicking on the speed buttons?

**Comment by Markus79** [comment]
Igen. Mindig elfelejtjük a legfontosabb dolgot. Megköszönni a készítők fáradtságos munkáját. Köszönöm Nektek. Nekem is van egy kérdésem: Mar készen van vagy meg javítgatjátok? Mert nem minden hibátlan még... De azért Köszi még egyszer.

**Comment by akarnokd** [comment]
Már egy ideje nem nyúltam hozzá, de "kész" azért még nincs. Sajnos kifutottam az ötletekből és időből, hogy hogyan lehetne megjavítani az AI-t, útkeresést és diplomáciát. Ide már egy AI-hoz értő programozó kell már.
