### ISSUE TITLE
Csillagtérkép bal klikk

### ISSUE THREAD

**Issue by shockace** [akarnokd/open-ig#946]
Sziasztok!

A csillagtérképen valamiért egyszer csak megszűnik a szimpla bal klikk lehetősége, így sem flottát, sem bolygót nem lehet kiválasztani.
A dupla klikket azonban érzékeli és megjeleníti a kolóniát, vagy a felszerelést.

Üdv,
ShockAce

**Comment by akarnokd** [comment]
Ilyenkor csak a térkép nem megy, vagy más képernyőelemre való kattintás sem?

**Comment by shockace** [comment]
Csak a térképen tapasztaltam és csak flották, ill. bolygók esetében.

**Comment by akarnokd** [comment]
Ez milyen plattformon van? Nem-e mozgás vagy támadás módba kapcsoltál? Az egered más játékban jól műķö

**Comment by shockace** [comment]
A mozgás / támadás-ra kapcsolás után jelentkezett a hiba.
Win 8.1 x64-et használok és az egérrel nincs baj máshol.
Viszont egy ideje nem tudom reprodukálni a hibát.
Ha jól láttam, más nem jelzett ilyet, igaz?

**Comment by akarnokd** [comment]
Ha megnyomod az M vagy A gombot, akkor célpont kijelölő módba vált és ki kell kelölnöd valamit, ami a flotta célpontjábá válik.

**Comment by shockace** [comment]
Igen, tudom, köszönöm.
Viszont nem tudtam magát a hajót kijelölni, hogy mozgassam, vagy támadjak vele.
Vagy ha a hajót sikerült is kijelölni a listából, akkor a támadni kívánt bolygót nem sikerült.
De mivel azóta sem sikerült a hibát újra előhozni (bezzeg 2 napig küzdöttem vele), lehet, hogy csak én voltam béna. Pedig nem ma kezdtem ezt a játékot. :)
Köszi a gyors supportot!
