### ISSUE TITLE
Win 7 X64 nem fut vagy csak nekem?

### ISSUE THREAD

**Issue by Markus79** [akarnokd/open-ig#947]
Üdv. Most telepitettem fel es nem fut, van java meg minden. Regen ment, ugyanezen a rendszeren csak masik procival, most nem akar elindulni csak a launcher fut. A jatek nem indul. Meg akartam nezni mire jutottatok 4 ev alatt, meg kedvenc jatek. Szep estet. Mi lehet a baj?

**Comment by Markus79** [comment]
Megoldodott Jdk kellett neki. 1.8 as. Lassuk mit tudtatok összehozni.

**Comment by akarnokd** [comment]
Szuper.
