### ISSUE TITLE
Indítási probléma

### ISSUE THREAD

**Issue by Janus30** [akarnokd/open-ig#950]
Nagy kedvencem volt annak idején az IG1, vagy 3-szor végigvittem. Megvan itthon eredetiben. Nagyon örültem mikor hallottam hogy csináltok belőle egy Open verziót. Ki is próbáltam az egyik gépemen (Athlon X2, 4GB Ram, Radeon HD3200 IGP), fut is szépen de a 4. szint környékén már nagyon belassul. Van 1 másik gépem is (Haswell Corei3, 8GB Ram, Radeon R9 270) gondoltam azon sokkal simábban fog menni. Hát sajnos belefutottam egy problémába. Letöltöttem az installert és ahelyett hogy elindítaná, felugrik egy winrar ablak és egyszerűen tömörített fileként értelmezi a .jar kiterjesztést és nem látok mást mint 3 mappa-t winrar alatt. Mit lehetne ezzel kezdeni?

**Comment by akarnokd** [comment]
Üdv. Valószínűleg az utóbbi gépeden nincs Java és emiatt a Winrar elhappolta a kiterjesztés kezelést. Javaslom, hogy telepítsd fel a legfrissebb [Java-t](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) és úgy próbáld a telepítőt. Szintén ajánlott frissíteni a régebbi gépeden is,

**Comment by Janus30** [comment]
Sajnos nem megy. 2 Java-t is próbáltam ( 7-es és 8-as). Winrarban kilőttem a filetársítást, mégse megy.

**Comment by akarnokd** [comment]
Próbáltad parancssorból indítani:

```
java -jar open-ig-launcher.jar
```

Ha nem megy, távolíts el minde Java-t és Winrar-t, majd először telepítsd újra a Java 8-at.

**Comment by Janus30** [comment]
A parancssoros indítás működik. Köszönöm szépen.
ui.: Sokkal simábban működik az erősebbik gépen! :)

**Comment by akarnokd** [comment]
Szuper!
