### ISSUE TITLE
Pirates in level 1 mission won't withdraw as promised.

### ISSUE THREAD

**Issue by Zalewa** [akarnokd/open-ig#956]
Video: https://www.youtube.com/watch?v=liNtBD2_XnQ

In pirate vs. pirate combat assignment pirates promise to withdraw after the discussion but then they attack anyway. I don't know what was the course of events here in the original game.

**Comment by akarnokd** [comment]
That seems to be a mistranslation in the original game (I've auto-built most chat text from the original files). In the Hungarian version, which is the reference, they say something like "let's look for another target" and attack your fleet. Then you have your fleet and the solo pirate to fend off. I think if you let the solo pirate die, they simply leave.

**Comment by Zalewa** [comment]
"Let's look for another target" also implies that they should retreat, unless either a) this is a deception written into the game's story or b) the pirates mean that you will be this another target which is simply confusing to the player. Mistranslations should be fixed though, even if the original game also had them :smile:

**Comment by akarnokd** [comment]
From mission design perspective, it is logical to attack the player since the whole level 1 was intended as a tutorial stage. As far as I remember, this is what happens in the original and I don't remember complaining about this specifically. Besides, the AI will flee if they take too much damage.
