### ISSUE TITLE
ha kevés az energia egy kolónián akkor egy épület sem üzemel

### ISSUE THREAD

**Issue by otter623** [akarnokd/open-ig#957]
Hello! Úgy vettem észre, hogy ha nem jut legalább 50% energiaszint minden épületre, akkor semmi sem üzemel. Az eredeti verzióban ilyenkor 1-1 épülettől megvonják teljesen az energiát és annak a fogyasztása már nem kerül beszámolása, így a többi részlegesen működik továbbra is. Ami logikusabb is, mert az nonszensz, hogy van energia, de inkább mindenre adnak 40%ot, és így semmi sem fog működni. Például emlékszem, hogy anno a new caroline-on, ha építettem egy radart, akkor már kevés volt az energia, de csak a szórakoztatóközpont esett ki 0-ra.

**Comment by akarnokd** [comment]
Üdv. Annó kísérleteztem némi automatizmussal, de végül nem került implementálásra, mert az optimális energiaelosztás kiszámítása nagyon költséges. A jelenlegi algoritmus minden épületnek arányosan juttat, max a sérültebbeknek kevesebbet. A játékosok meg szívesen kapcsolgatták az épületeket maguk.

Kicsit régen volt már, így nem esküszöm meg rá, de ha a bolygót AI menedzseltre rakod, az elvileg kapcsolgatja az épületeket annak függvényében, hogy van-e elég áram; de persze az AI mást is fog csinálni.

**Comment by otter623** [comment]
Értem köszi. Annyira nem idegesítő, csak hozzá kell szokni, hogy arra a kis időre amíg észreveszi az ember, leáll minden, Ezekszerint az ilyen dolgokhoz az eredeti algoritmusok nincsenek meg, nem azokat módosítottad csak?

**Comment by akarnokd** [comment]
Semmilyen kód nincs meg az eredetiből, ami van, az megfigyelés alapján, illetve saját kútfőből készült, igy sosem lesz 100%-ban egyező az eredetivel.
