### ISSUE TITLE
Research screen loses its content if a research completes

### ISSUE THREAD

**Issue by akarnokd** [akarnokd/open-ig#959]
(Unconfirmed)

Player reports that when he has the research screen open and a research is about to complete, the second the research completes the UI loses the tech icons and the animation.

It is possible the completion of the research sets the UI's current research to null and the game crashes or simply doesn't display anything.

**Comment by Gosu4095** [comment]
I can confirm this happens, it's almost second nature to me now to do the necessary clicks to bring back the UI.

**Comment by akarnokd** [comment]
Fixed via #962
