### ISSUE TITLE
auto-repair

### ISSUE THREAD

**Issue by law7441** [akarnokd/open-ig#965]
it not working, I have select but have to do the repair to building maunal, never had these issue before.

Game version: 0.95.206

Operating System: (e.g., Windows 7 x86, Windows XP 64-bit)

winsdows 7 64-bit
Java runtime version: (run java -version)
version 8 update 77

Installed using the Launcher? (yes, no)

yes

**Comment by akarnokd** [comment]
There is an auto-repair money limit in the gameplay settings.

**Comment by law7441** [comment]
make no difference, even if increase the limit and doesn't work at the start of the campigen when not used any of the limit.

**Comment by akarnokd** [comment]
Works for me. Set the limit to 0, enable auto-repair, start a new campaign and see Achilles repaired.

**Comment by law7441** [comment]
I try that, just never had to do that before, was using 0.95.204 than through on older computer, most be some in the new updates stop it.

**Comment by akarnokd** [comment]
That setting is part of a save. If you load something different, it can change.

**Comment by law7441** [comment]
puttng to 0 in game worked thank you, and for saved game too.
