### ISSUE TITLE
AI builds prefab housing when it needs power

### ISSUE THREAD

**Issue by Gosu4095** [akarnokd/open-ig#967]
The old problem with the AI building lots of prefab housing when it requires energy has come back. Running the latest version.

**Comment by akarnokd** [comment]
Could you send a safe? akarnokd at gmail.com

**Comment by Gosu4095** [comment]
Certainly, sorry for delayed reply. Sending now. All but 1 of the AI were affected in this skirmish game I think.

**Comment by akarnokd** [comment]
Thanks. Fixed via https://github.com/akarnokd/open-ig/commit/4e17392fd6ba0ffeee76fa0d7735162321d2c8e2
