### ISSUE TITLE
A.i seems to be ignoring colony needs

### ISSUE THREAD

**Issue by Sarounk** [akarnokd/open-ig#968]
Hi, i've been playing this game and noticed that the a.i is ignoring some colony needs.

Food

Living space

[save-2016-05-23-20-32-27-035.xml.gz.zip](https://github.com/akarnokd/open-ig/files/278585/save-2016-05-23-20-32-27-035.xml.gz.zip)
[save-2016-05-23-20-59-51-346.xml.gz.zip](https://github.com/akarnokd/open-ig/files/278584/save-2016-05-23-20-59-51-346.xml.gz.zip)

**Comment by akarnokd** [comment]
Thanks. Yesterday's changes went to far. Release 0.95.208 is out and AI should work now.

**Comment by Sarounk** [comment]
Oh ok, thanks.
