### ISSUE TITLE
Defensive Structures Surrendering at 51%

### ISSUE THREAD

**Issue by mansam** [akarnokd/open-ig#969]
I've noticed while playing through Commander in the campaign that if my last Barracks hits 51% damage, the ground battle ends and I lose the planet. My defensive structures aren't supposed to surrender like that.

Possibly related odd behavior:
During such a ground battle, the AI goes around damaging all my Nuclear Plants to 51% rather than destroying them. That's weird and inconsistent with the original game. If I then lose the ground battle with all those Nuclear Plants at 51% percent and then retake the planet immediately, all structures that were damaged to 51% are gone from the planet. This suggests to me that the game is treating buildings that reach 51% damage as though they are destroyed, but I don't have a good way to test that hypothesis.

**Comment by akarnokd** [comment]
Yes, the AI utilizes the mechanics surrounding the buildings. It damages power plants because loosing power on the barracks disables them. If all barracks are destroyed or disabled and no attack-capable enemy unit remains, the battle is won. In addition, by not destroying the buildings, the AI can then later sell them for money (or repair them if that's cheaper).

**Comment by mansam** [comment]
I see that regarding my last comment that the AI might have sold all those power plants, but in that case they left their newly captured world with no power.

Player controlled Barracks, in the original game, continue fighting until they are destroyed or are totally deprived of power. Defensive structures are prioritized for power during ground battles, so to starve them of power you need to totally destroy nearly every source of power on a planet. Open-IG doesn't seem to share that behavior.

In either case, Barracks with power shouldn't be surrendering at 51%.

**Comment by Gosu4095** [comment]
The AI seems to prefer to destroy significantly damaged buildings and rebuild them. Perhaps it is cheaper/quicker than repairing after certain % of damage?  If you give AI control immediately on campaign it will demolish/sell all structures on Achilles and build a colony hub, I assume this explains the behaviour. This is easily testable.

**Comment by mansam** [comment]
Relating to your comment @Gosu4095, the Garthogs are the one race other than the player that *never*, under any circumstance, surrender their Fortresses in the actual game, so they probably shouldn't in OpenIG. This means that the only way to acquire that technology in Commander rank is to capture a planet from the Morgath or Ychoms.

**Comment by Gosu4095** [comment]
Well you can always capture a Garthog planet as it is constructing a Fortress and you will obtain the plans ;)

**Comment by mansam** [comment]
True, but pretty tricky ;)
