### ISSUE TITLE
Bombs and missiles 

### ISSUE THREAD

**Issue by oizdar** [akarnokd/open-ig#971]
Bombs should attack only planetary defence. Missiles should attack only spaceships and starbases . But now it is possible to attack everything by both.

**Comment by akarnokd** [comment]
There is an option "Fire target specific rockets/bombs only" on the settings/gameplay screen:

![image](https://cloud.githubusercontent.com/assets/1269832/15615314/debcd6da-243d-11e6-9a7b-7fad86256d6d.png)

**Comment by oizdar** [comment]
Ok thanks :) but in my opinion it should be default on .
