### ISSUE TITLE
Tax income per hour vs per day??

### ISSUE THREAD

**Issue by Gosu4095** [akarnokd/open-ig#972]
My friend and I were both running the latest version, on his computer he receives tax income per hour and on mine I receive tax income per day. I cannot figure out how to change this, please advise!

Also sorry for a very basic question, but where is explanation of variables in skirmish mode such as Galaxy Template etc it's hard to see what the difference is and I can't find the guide on github.

**Comment by akarnokd** [comment]
There is an option "Continuous money/morale calculation" on the settings/gameplay screen:

![image](https://cloud.githubusercontent.com/assets/1269832/15615314/debcd6da-243d-11e6-9a7b-7fad86256d6d.png)

**Comment by Gosu4095** [comment]
I am glad I am not blind, I do not have this option. I am running 0.95.208...

**Comment by Gosu4095** [comment]
Ah, it seems this option is available from the main menu settings, but not from in game.

**Comment by akarnokd** [comment]
> Option still not present in game settings screen.

This is deliberate as it would create problems when toggled live such as double accounting or lost funds.
