### ISSUE TITLE
Certificate problem when running launcher..

### ISSUE THREAD

**Issue by vrtikais** [akarnokd/open-ig#973]
Hello I have a problem running the launcher on linux platform.. Same problem when I use openjdk-8 or oracle java 8
other java version segfaults while running it maybe there is some missing CA in java?

thank you in advance
`java -Djavax.net.debug=all -jar open-ig-launcher.jar`

gives output

https://gist.github.com/akarnokd/c4e3fa70abf8cebd57f6dbcf846e2e6d

**Comment by akarnokd** [comment]
Your java install appears to be outdated or corrupted. I recommend reinstalling it completely.

**Comment by vrtikais** [comment]
It was issue with ca-certificates-java package.. For some reason it's postinst script fails... Reinstall does not help I had to call its postinst script manually
`sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure`

it is related to
https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1396760

Anyway thank you for your quick reaction
