### ISSUE TITLE
Level 3 - Mission "Prototype"

### ISSUE THREAD

**Issue by Silver1983** [akarnokd/open-ig#974]
Version: 0.95.208
Mission: Level 3 - Escort prototype (Destroyer 2) from Zeuson to Centronom.

What happend: The prototype got destroyed. Still I could complete the mission, got the thank you video and even saw the fleet "Prototype" (which was now empty) arriving at Centronom.

What should happen: The mission should fail if the Prototype got destroyed regardless of me winning the fight or not.

**Comment by akarnokd** [comment]
Sounds like a mission bug. Do you happen to have a save before that mission?

**Comment by Silver1983** [comment]
As a matter of fact I do :)

[savegame.zip](https://github.com/akarnokd/open-ig/files/299378/savegame.zip)

**Comment by akarnokd** [comment]
Thanks and sorry for the delayed answer. I'm quite busy now but I'll try to check and address the issue in a couple of days unless somebody else wants to look at the relevant `Mission` and see why the failure condition is not applied.

**Comment by mansam** [comment]
The mission checks to see whether the prototype fleet still exists, and it sounds like for some reason the fleet still exists after the space battle even if its contents are destroyed. I'll poke around and see what I can find.

**Comment by p-smith** [comment]
The fleet is not necessarily empty after the battle. There are also 4 fighters in the prototype fleet, so if one of them survives (even if the prototype goes down), the fleet will still exist at the end of the battle.

If the fighters die as well, the mission (correctly) fails.

**Comment by mansam** [comment]
Good catch, that makes it an easy fix.

**Comment by akarnokd** [comment]
Thanks for the evaluation @p-smith and fix @mansam . Fix #975 merged. I'll release 209 this week (I want to see if any other simpler fixes can be done).
