### ISSUE TITLE
AI épület fejlesztés

### ISSUE THREAD

**Issue by Babjatekos** [akarnokd/open-ig#976]
Annyi kérdéssel zavarnék hogy az AI egyáltalán nem fejleszti a lakóházakat, erőműveket az élelmiszer gyárakat, rendőrséget kórházat, helyette inkább újakat épít mindig. Az Atomerőműveket sem cseréli le hatékonyabbra pl nap erőműre - ha már kifejlesztette -.
Gyanakszom hogy a módosításaim beletúrhattak az AI-ba vagy kiakasztották. - nagyobb bolygó méret, hatékonyabb kórház és rendőrség -

Igazából a kérdésem az lenne hogy mikor kezdi fejleszteni a fent felsorolt építményeket? Régebben mintha valami olyat írtál volna hogy helyhiányában? Vagy rosszul emlékszem? 

amúgy 0.95.208 verzióval is teszteltem, semmi moddolással és úgysem nagyon akaródzott neki fenti épületeket fejleszteni.

Ja és hiába van bekapcsolva skrimish-ben a több építhető gyár és gazdasági épület meg kutató labor, egyedül csak a labort épít többet.

Tervezed valamikor az AI kicsit feljavitását? Mert pl az agresszivitása sem valami eget rengető Hard beállításnál.

**Comment by akarnokd** [comment]
A jelenlegi AI heurisztika az, hogy amíg van hely a bolygón, addig nem fejleszt létező épületet. Ha van elég pénze, akkor kategórián belül jobb épületet épít (atomerőmű -> fúziós erőmű). A fejlesztés ugyanannyiba kerül, mint egy új építése, de nem ad annyi előnyt.

> Tervezed valamikor az AI kicsit feljavitását? Mert pl az agresszivitása sem valami eget rengető Hard beállításnál.

Sajnos a játékmechanika és az AI heurisztikák konfliktusban vannak. Az eredeti játék csalt, pediódikusan küldte rád a full flottákat. Itt megpróbálja eldönteni, hogy kit és mikor támadjon, de a balansz miatt nem jut messzire (pl. full garthog flotta simán lepattan egy ychom bolygóvédelemről). Továbbá az AI is ugyanolyan gazdasági szabályok szerint játszik, így nem mindig van pénze, mert a többi fajnak nincs kereskedelmi űrkikötője és bankja.

**Comment by Babjatekos** [comment]
Régóta nem láttam azt, hogy valamikor is fejlesztette volna a gép pl erőművet ha kifogyott a helyből vagy élelmiszer gyárat vagy bármi mást a Hajó/felszerelés/fegyver gyár kivételével. Mind1 ezen még talán túlteszem magam. Bár ha gondolod épp most csinálok egy játékot - alap nem moddolt - ahol szintén előjött már a nem fejlesztés, becsatolhatom a mentést ha érdekel.

Azt megfigyeltem hogy a gépi fajok egymással jól el háboruskodnak, és többé kevésbé egyenlő az erőviszony, max 1 faj - mindig más - aki kihal mert gyengébb volt a kutatásokban. (alap beállítások, hard AI, 200 bolygó, általam nagyra szerkesztett térkép) Az is érdekes hogy néha néha meg megkóstol az AI - ez is mindig más faj - egy egy full feltöltött aktuális fejlettségének megfelelő szintű flottával a gyengébb bolygómnál. 
Egymást elég szépen aprítják ide oda cserélgetik a bolygókat stb. engem gondolom azért nem támadnak annyira mert általában na jó mindig kutatásban jóval előttük járok.

Egy kérdés/kérés: kutatásnál megoldható valahogy hogy - akármelyik fajjal vagy - pl a földi egységek mindegyikét tudj gyártani, azt is ami a másik fajoknak van akár speciális egysége is? 
Erre nehéz lenne egy kiegészítés pipálható opciót csinálni a játék beállításánál? - mint a mindenki gyárthat minden fajta épületet - Én próbálkoztam megoldani de kifújtam vele sajna nem sikerült. :(
Lehetne egy ilyen mod-ot csinálni? 
Örülnék neki ha lenne variációs lehetőség felszíni egységeknél mindegyik fajnál, és lehet érdekesebbé tenné a földi harcokat még AI vs AI ellen.

**Comment by akarnokd** [comment]
Skirmishben elvileg bővített technológiával játszanak a fajok. Sajnos akármilyen földi egységet nem lehet gyártani, mert a képernyőn csak 7 slot van.
