### ISSUE TITLE
Strange graphical bugs

### ISSUE THREAD

**Issue by Silver1983** [akarnokd/open-ig#977]
Version: 0.95.208
What happens: Cutscenes become unwatchable, because part of the image gets duplicated on the side of the screen (image 1). In addition to that images of buttons disappear and some kind of placeholder is displayed (image 2).

When does it happen: It is repeatable by watching one of the long intro cutscenes via the video player ingame, but it also happens from time to time after long game sessions. No savegame is availabe.

Sorry for the image quality. I did those with my mobile :)

![image 1](https://cloud.githubusercontent.com/assets/4612520/15943081/981dfff2-2e87-11e6-9594-3fef60644b5f.jpg)
![image 2](https://cloud.githubusercontent.com/assets/4612520/15943082/98213ec4-2e87-11e6-88b6-28f902406468.jpg)

**Comment by akarnokd** [comment]
Does it happen if you don't run in fullscreen? What's your Java version?

**Comment by Silver1983** [comment]
Version 8 Update 91, so it should be the newest version.

Until now it did not happen in maximized window mode. Any idea what it could be?

**Comment by akarnokd** [comment]
Could be a driver problem. Are you on Windows?

**Comment by Silver1983** [comment]
Windows 10 Pro 64bit

**Comment by akarnokd** [comment]
Make sure you have the latest graphics drivers. Also try running in a window with borders and maximized.

**Comment by Silver1983** [comment]
Well, I updated my drivers (GTX 780, were maybe 3 month old) and so far I didn't experience it again. Will keep an eye on it.

I'm no real fan of playing games in a window, no matter how big. Immersion and so forth...

**Comment by Silver1983** [comment]
It just happend again. Fullscreen. Newest driver. Started the game, played a video (level_4_intro) and after 3 seconds the mentioned behaviour started.

**Comment by akarnokd** [comment]
Since the rendering code for videos hasn't changed for quite some years now, all I can think of that its a bug with how Java interacts with DirectX. Try the diagnostic options from the setting screen, not-ingame:

![image](https://cloud.githubusercontent.com/assets/1269832/15990326/ee186a00-308f-11e6-9625-0c2fed9fb3e5.png)



By the way, is there a screen open (like the equipment screen) before the video gets played?

**Comment by Silver1983** [comment]
Most of the time there is no opened screen.  I'll try disabling the graphics options and see what happens.

**Comment by akarnokd** [comment]
Closing for now. It's been 1 year with both Windows and Java updated several times. I haven't encountered such artifacts on my Windows 10 laptop.
