### ISSUE TITLE
Colony screen behaviour

### ISSUE THREAD

**Issue by Silver1983** [akarnokd/open-ig#978]
Version 0.95.208

What happens: I look at a colony at the colony screen. I zoom out to see more of it. I click next. The next colony is displayed but the colony screen shows the lower right part if the map and I have to to recenter the colony. This does not happen if I do not zoom out.

What should happen: The colony screen should ALWAYS center my chosen viewpoint, regardless of the zoom level.

**Comment by akarnokd** [comment]
Colonies have different sizes but the position doesn't change between planets, so you may end up looking at nothing.

I'm open to different behavior. At one time I had it always centered but didn't really work out. A possible solution is to get the center point's location proportional to the current planet's size and when moving to the next, reposition the view.

For example (1D), planet with = 100, center is looking at 20 -> 0.2 relative. Going to the next planet with with = 200, the view should be positioned to 200 * 0.2 = 40.

**Comment by Silver1983** [comment]
If I get this right you want it to focus on the center of the screen relatively to the map? This sounds good then.

Another possible solution: Remember each position. This could give a real advantage: You could order a new building on colony 1, jump to the other colonies and check whatever you wanna check and then return to colony 1, while the camera is still focussing on your last action at that particular colony.
