### ISSUE TITLE
How to turn of debug(?) informations

### ISSUE THREAD

**Issue by Silver1983** [akarnokd/open-ig#979]
A few updates ago 2 informations became visible while playing in the upper left side of the screen. Changing "ms" (millisecond?) numbers can be seen since then the whole time and there doesn't seem to be an option to turn this of. How do I do it?

**Comment by akarnokd** [comment]
Use CTRL+ F to turn it off. I'll disable it in the upcoming release.

**Comment by akarnokd** [comment]
Fixed in the upcoming 0.95.209 release.
