### ISSUE TITLE
Thorin: Wrong shotcuts when entering elevator

### ISSUE THREAD

**Issue by Silver1983** [akarnokd/open-ig#981]
Level 4 - Thorin. Leave the bar and head to the bridge. Enter the elevator. Click. You return to the corridor you just came from.

If I am not mistaken corridor and bridge shortcuts should be changed. I'll attach a savegame where you're in front of the elevator.

[Corridor.zip](https://github.com/akarnokd/open-ig/files/310697/Corridor.zip)

**Comment by akarnokd** [comment]
The elevator is a place and can't consider your implied travel direction. The tooltips should be clear on the clickable areas: center means go to the corridor, bottom means go to the bridge.

**Comment by Silver1983** [comment]
So it can't know from which side I am coming? The tooltips make it very obvious, that's for sure.
