### ISSUE TITLE
No easy way of entering a name for savegames

### ISSUE THREAD

**Issue by Silver1983** [akarnokd/open-ig#982]
Right now when I play a game, save it and want to save it again OIG remembers the name of the last savegame. That's nice. 
If I quit OIG, start it again and want to save now, the "name" field is empty. Lazy as I am I don't wont to enter a name for a savegame again. Instead I just pick one from the list. The problem is: The name will not be taken over into the name field.So now I have two options: I either reenter a name for my savegame or I do a savegame without a name :/

Could you implement the possibility to just click on a savegame and save the game under this name by just clicking save?

EDIT: By rightclicking I can use a name! Not very intuitive but I got it :D :D That's what I mean. Your way works but it is not always the way you'd expect it to work.

**Comment by akarnokd** [comment]
Not sure how to advertise this feature (without introducing clutter or obscure documentation people wouldn't likely find) so decided not to take action. Anyway, thanks for the report.
