### ISSUE TITLE
infected traders relaunch despite made return peacefully

### ISSUE THREAD

**Issue by anonymissimus** [akarnokd/open-ig#989]
from http://www.ign.com/faqs/2004/imperium-galactica-walkthrough-393220
"(1) 
select the lines that appear at the very top of the text box to converse with 
the trader..., or (2) engage them with fighters 
until you see something like "Don't shoot... we'll turn around" in the text 
box, then pull your fighters off and let the trader flee. You may notice that 
if you use method 2, rather than 1, traders will keep on trying to leave the 
planet. If you use the first method, they tend not to try and break the 
blockade a second time."

This apparent functionality of the original game seems to miss from open ig, as they relaunch again and again anyway.

**Comment by akarnokd** [comment]
If you send them back, they stay longer on the planet but eventually they do launch again. It doesn't matter if you shot or chatted with them.

**Comment by anonymissimus** [comment]
Well, yes, and that's the bug, if what the old walkthrough says is true. I never played the original.

**Comment by akarnokd** [comment]
Thanks for the feedback. There are a lot of things not exactly mirrored from the original and others are deliberately different. Changing their behavior requires modifications to the trader management which has the risk of breaking other behavior and no good way of testing (traders are highly probabilistic). Therefore, I'm sorry but this is a wontfix issue.

**Comment by mansam** [comment]
@anonymissimus  That old walkthru is wrong anyway--- they absolutely would relaunch in the old game. The only way to be sure how the original plays is to play it. ;)
