### ISSUE TITLE
Game not loading ... jumps back to main Menu

### ISSUE THREAD

**Issue by michael-s99** [akarnokd/open-ig#991]
Hi,

yesterday evening I saved my Level 4 game. This morning, I tried to resume the game. First the Disc with "Loading ..." appears, then the game jumpes back to the main menu.

None of the last four savegames are working.

Is there maybe some error log that I can provide to you`?

BR
Michael

**Comment by akarnokd** [comment]
There is a log file in the main directory: `open-ig.log` and please send me one of the saves that doesn't load.

**Comment by michael-s99** [comment]
Seems the planet "new caroline" is damaged in the xml save file.

now I remember .... the planet was mine but there has been no bulidings anymore an I cound not build the center.

can you repair the savegame for me?
[save-2016-09-16-00-55-32-655.xml.gz](https://githu
[open-ig.log.zip](https://github.com/akarnokd/open-ig/files/477466/open-ig.log.zip)
b.com/akarnokd/open-ig/files/477465/save-2016-09-16-00-55-32-655.xml.gz)

**Comment by michael-s99** [comment]
logfile
[open-ig.log.zip](https://github.com/akarnokd/open-ig/files/477468/open-ig.log.zip)

**Comment by akarnokd** [comment]
Try this:

[save-2016-09-16-00-55-32-656.xml.gz](https://github.com/akarnokd/open-ig/files/477474/save-2016-09-16-00-55-32-656.xml.gz)

**Comment by michael-s99** [comment]
works! thanks a lot :)

**Comment by akarnokd** [comment]
@rdubisz Unless you found yourself something else, this could be an excellent 2nd PR. I'm not sure how to trigger the original case but it should be possible to repair the state when loading the planet information.
