### ISSUE TITLE
Installer glitch

### ISSUE THREAD

**Issue by Arekonator** [akarnokd/open-ig#992]
Hello, i have problem with installer. When i launch instalation, it tries to connect to the googledrive that doesnt exist anymore.
I tried downloading all the launcher files manually, but when i launch it, it still tries to connect, instead of installing from files already on the drive.

[open-ig log.txt](https://github.com/akarnokd/open-ig/files/504105/open-ig.log.txt)

**Comment by akarnokd** [comment]
Looks like Google stopped its hosting service and the files can no longer be accessed that way. I'll try to upload the files here and see if it can work or not.

**Comment by akarnokd** [comment]
I've changed the hosting of the files. Restart the launcher and it should work now.
