### ISSUE TITLE
Abillitys from alien special ground units implemented on Empire special ground units ?

### ISSUE THREAD

**Issue by Calatorul** [akarnokd/open-ig#994]
Which is the file i have to open in order to edite combat ground Units ? Such as def. att. power, Speed, Special abillitys and so on. 
The armour bar of ground combat Units has the same thickness for every unit. In the original game was different for every armour strenght.
Thnkx in advice !

**Comment by akarnokd** [comment]
The properties of vehicles are stored [here](https://github.com/akarnokd/open-ig/blob/master/data/generic/campaign/main/battle.xml#L343) but you can't change the height of the health bar. It is fixed and the same for every ground vehicle.

**Comment by Calatorul** [comment]
Thnkx for the very fast answer ! We'll have any update to fix the height of the health bar in the near future ? To recognize faster different armour strenghtness.

**Comment by akarnokd** [comment]
No. I decided a long time ago that certain things won't be replicated in a 1:1 fashion.

**Comment by Calatorul** [comment]
Are changes applied to the current saved game Progress ? or i have to start a new game to see any changes made ?

**Comment by akarnokd** [comment]
If you update the xml in the zip file, that becomes visible when you reload a save from the main menu (otherwise, a quick load doesn't reload resources of an ongoing game).
