### ISSUE TITLE
Földi harc űrcsata nélkül - bug

### ISSUE THREAD

**Issue by afterparty007** [akarnokd/open-ig#995]
Ha bolygó támadásnál az űrcsatában:
1. visszavonulást nyomunk, és elkezd minden egységünk kivonulni,
2. visszavonjuk a visszavonulást (az egységek még mindig vonulnak ki)
3. A kivonuló csatahajókról kilövünk minimum egy bombát a lövegekre.

Az eredmény: elkezdődik a földi csata, és ha győzünk megmaradnak az űrvédelmi épületek is.

**Comment by akarnokd** [comment]
Thanks. I don't know when will I have the time to fix this. PR welcome.
