### ISSUE TITLE
Failure to get game to launch

### ISSUE THREAD

**Issue by DionZeromus** [akarnokd/open-ig#998]
I recently downloaded OIG after a long while and a computer reformat.  Ran the launcher, no issues there.  However, when I attempt to actually start the game, I keep getting the first time set up.  I click okay, and that's it.  Closes the window and leaves me on the launcher.  I've verified the installation, according to the launcher it's good.

**Comment by akarnokd** [comment]
What platform?

Try running the main jar file directly or from command line with java -jar <filename here>

**Comment by DionZeromus** [comment]
Win10 (64-bit), Java Runtime Environment 8, update 121, build 1.8.0_121-b13.  Other than OS, and HDD, and obviously a more updated Java, this is the same computer I played on originally.  I had attempted to launch the game directly with the open-ig-0.95.210.jar, but it still wouldn't launch.

As for the command line, where would I apply that?  I tend not to futz with command line bits as I'm not exactly the most knowledgeable or experienced with such things.

**Comment by akarnokd** [comment]
> As for the command line, where would I apply that?

So it can print an error message if there is one.

**Comment by DionZeromus** [comment]
What command do I apply and where?

**Comment by akarnokd** [comment]
```
java -Xmx1G -jar open-ig-0.95.210.jar -memonce
```

It should print something to the console window.

**Comment by DionZeromus** [comment]
Ummm, where do I put that in?  I don't know how to get .jar's to do command lines...

**Comment by akarnokd** [comment]
In the Windows start menu, type in `cmd.exe`, press <kbd>Enter</kbd>, then type in

```
java -Xmx1G -jar open-ig-0.95.210.jar -memonce
```
then press <kbd>Enter</kbd>

**Comment by DionZeromus** [comment]
Doing that revealed an issue I had with another .jar program I recently got.

"Error occurred during initialization of VM
Could not reserve enough space for 1048576KB object heap"
Apparently trying to run more than 512mb of memory is more than my Java can handle, which is weird.

**Comment by akarnokd** [comment]
I suggest uninstalling all Java (add/remove programs) and reinstalling Java 8 update 121 x64 and see if that works.

**Comment by DionZeromus** [comment]
Thank you, that helped fix it.  As apparently I was lacking in Java's x64 bit version, and thusly only running on 32-bit.
